### ISSUE TITLE
Support for Holmes Humidifier. 

### ISSUE THREAD

**Issue by rhuss2** [bwp91/homebridge-platform-wemo#184]
**Is your feature request related to a problem? Please describe.**
Support for the Wemo Homes Humidifier. I believe it is supported on openHAB.

**Comment by bwp91** [comment]
Would be happy to look into supporting the humidifier. let me know!

**Comment by rhuss2** [comment]
It would be great to have it on homebridge.

**Comment by bwp91** [comment]
Could we message on the Homebridge Discord?:
https://discord.gg/7X36mdw
