### ISSUE TITLE
Unable to find devices

### ISSUE THREAD

**Issue by fpy-homeb** [bwp91/homebridge-platform-wemo#207]
**What issue do you have? Please be as thorough and explicit as possible.**

Ran update to pi for all latest packages, updated Wemo plug in for homebridge, now no devices found

**Details of your setup.**
Do you use Homebridge or HOOBS?

Homebridge

Which version of Homebridge/HOOBS do you have?

1.1.6

Which version of this plugin (homebridge-platform-wemo) do you have?

1.6.2

**Please paste any relevant logs below.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

No errors in logs

**Comment by bwp91** [comment]
Hi, 
Sometimes the devices can take a couple of minutes to discover, also depending on if you have set a custom discovery interval.
Could you paste the wemo platform part of your homebridge config here?

**Comment by fpy-homeb** [comment]
"name": "BelkinWeMo",
"platform": "Belkinwemo"

**Comment by bwp91** [comment]
Please try changing the second line to:
`"platform": "BelkinWeMo"`

**Comment by fpy-homeb** [comment]
Done, no change

**Comment by bwp91** [comment]
Could you try running this?
https://github.com/rudders/wemo-discover
To see if this can detect your devices?

**Comment by fpy-homeb** [comment]
sudo npm install https://github.com/rudders/wemo-discover.git
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ wemo-discover@1.0.1
added 58 packages from 115 contributors and audited 58 packages in 31.937s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

I am getting the above when I try and install that from git?

**Comment by fpy-homeb** [comment]
hey, thank you for your help, there was an update to my wemo link and it needed to be restarted (4 times) now its picking everything up.

**Comment by bwp91** [comment]
Ah excellent glad the solution was found 👍
