### ISSUE TITLE
Wemo Holmes Heater Support?

### ISSUE THREAD

**Issue by wilbsww** [bwp91/homebridge-platform-wemo#209]
Is there any possibility of adding compatibility for the Wemo Holmes Heater? I’ve been attempting for years to add this device to my array but never been able to do so, even though the wemo documents claim support for such device

**Comment by bwp91** [comment]
Hi @wilbsww,
Can certainly give it a try! 

> even though the wemo documents claim support for such device

The wemo-client dependency that this plugin uses claims support for this device. But this plugin so far doesn't support this device as per the plugin wiki.

It would be a lot easier if I could message you on the (Homebridge Discord)[https://discord.gg/7X36mdw] as as I don't own this device I will need a lot of your time to possibly add support for this device.

**Comment by wilbsww** [comment]
Thats what I meant but worded poorly (that the dependency supports it)! 

I have the lowest of barebones ability to code things....basically meaning i can follow directions well but lack originality! I tried years back to get the wemo heater dependency to work and never could...prob cause of my black-tech thumb

**Comment by bwp91** [comment]
Could we message on the link I sent you (if you're not already on there)? My username is bwp91 or let me know yours if you can't find me

**Comment by danielsza** [comment]
I too would be willing to help getting the heater supported. I have the larger one that lists as HeaterA.

Also I noticed the other day that both my wemo heater and crockpot now are added to my home, but both say not supported 
![EAA9904A-4530-4112-9C74-4C13E7E7D857](https://user-images.githubusercontent.com/6549750/98564777-ca47f500-227a-11eb-89f8-204ebd9808ae.jpeg)

**Comment by bwp91** [comment]
Hi @danielsza 
Adding support for a new device will need a lot of back and forth messaging, ideally via the [Homebridge Discord](https://discord.gg/7X36mdw) if you're happy to on there :)

**Comment by danielsza** [comment]
I’ve just joined... let me know how I can help.

**Comment by bwp91** [comment]
Experimental support for the Heaters added in v2.3.0.
Any feedback would be super.
Thanks!
