### ISSUE TITLE
Wemo Update changed Wemo Makers function

### ISSUE THREAD

**Issue by WayneKP** [bwp91/homebridge-platform-wemo#211]
Hello, yesterday my Wemo makers which I use for Garage door openers had 2 nice accessories showing Garage doors opening and closing on my Homebridge UI and on my Apple Home App but since the Wemo update to the Homebridge plugin I now have 4 accessories, 2 switches Powered "off/on" and 2 sensors which I was able to set as Garage Door Openers but they now have 2 separate functions. Can I change it back to how it was working before ? Now I have to switch garage doors Power "on/off" to open the doors and the sensors show the opening and closing whereas before I had 2 which controlled opening and closing and showed just as a Garage door opening or closing
![Wemo Config](https://user-images.githubusercontent.com/37004336/97372230-dd63d800-18fe-11eb-8e27-b975f1a2b000.png)
![Wemo Maker](https://user-images.githubusercontent.com/37004336/97372401-49464080-18ff-11eb-9533-6cea7e4142fe.png)
![Wemo](https://user-images.githubusercontent.com/37004336/97372022-54e53780-18fe-11eb-84ac-7e2ae5d2d937.png)

**Comment by WayneKP** [comment]
> Now I have to switch garage doors Power "on/off" to open the doors and the sensors show the opening and closing whereas before I had 2 which controlled opening and closing and showed just as a Garage door opening or closing

king

**Comment by jammmyb** [comment]
Just updated homebridge and plug-ins and experienced the same thing. 

What do I need to do to restore it back to how it was? One button with. Garage door open/closed?

**Comment by bwp91** [comment]
Hi @jammmyb 
You can change the maker type through the plugin settings in the "Wemo Makers" section. Just need the serial number and select the type you wish it to be

**Comment by jammmyb** [comment]
@bwp91 

Saw the other thread about it. I’d put 8 instead of S in the serial number and that was why I could access it but it wouldn’t change to a garage opener switch. 

Thanks for the advice. 👍
