### ISSUE TITLE
Wemo Update, now accessories not working home app

### ISSUE THREAD

**Issue by WayneKP** [bwp91/homebridge-platform-wemo#212]
I use Wemo makers for 2 Garage Door Openers and since I did the last Homebridge Wemo plugin update I cannot get the doors to open with a "tap" on the Apple Home app, it only opens the "slider" and I have to slide to open or if I drill down on the settings for the garage door to the 2 accessories for the door which shows the "sensor" and the "Door" and if I "tap" on the door icon it will open the door yet on the homebridge app UI , tapping on the Garage door icon works fine . I tried changing the "Contact sensor state" to a "Garage door opener"  but it still brought up a "slider"  
Before the update it worked with a "tap" and the garage door would open and I think before the sensor and switch weren't shown as 2 accessories or maybe at least when I added them in the home app it came up as a garage door, not as a sensor like it does now ??? don't know if this has anything to do with the ssue

...

Homebridge
V1.2.3
homebridge-platform-wemo v2.1.0
It's not showing any error logs
...
![Wemo Home app](https://user-images.githubusercontent.com/37004336/97383167-ad293300-1918-11eb-8e20-184ab9be79e3.png)
![IMG_0565](https://user-images.githubusercontent.com/37004336/97383196-c4682080-1918-11eb-88ef-9a9800faaf9a.jpg)
![IMG_0566](https://user-images.githubusercontent.com/37004336/97383210-caf69800-1918-11eb-98d9-ecdb152f16bd.jpg)
![Slider](https://user-images.githubusercontent.com/37004336/97383661-d8605200-1919-11eb-861f-a098fd2290b4.PNG)

**Comment by WayneKP** [comment]
![Uploading Wemo Config.png…]()

**Comment by WayneKP** [comment]
![Wemo Config](https://user-images.githubusercontent.com/37004336/97384633-d0a1ad00-191b-11eb-9436-7cbf1d444e83.png)

**Comment by vsidlu** [comment]
i had the same problem. do not know what causes it. my workaround was - set sensor to NO in wemo app.  then readd maker and then change sensor to YES in wemo app.

**Comment by WayneKP** [comment]
Great, Thanks, that works
I can’t remember ever seeing 2 accessories on one icon like that on previous homebridge Wemo update so I figured the sensor was an issue but didn’t know how to get it off the Apple home app but happy now it’s back the way it was 

Kind Regards
Wayne Pulbrook 

Mobile 0417439539
wayne_pulbrook@yahoo.com

**Comment by vsidlu** [comment]
i use this plugin for very long time and this was something i see first time. i even rolled down to version 1.6 and nothing changed. i was lucky with switching sensor to NO.

**Comment by wallacepost** [comment]
Hi, similar issue after updated last night. the garage door become a button, how to change back how it was ?


![568FC4D8-CDD6-462F-8ED6-D707FC91C30B](https://user-images.githubusercontent.com/65918663/97422208-9f4bd000-1961-11eb-875b-0f414491f2f4.png)
![63620A93-3CF2-4E1C-89C3-E53F99822F5D](https://user-images.githubusercontent.com/65918663/97422227-a5da4780-1961-11eb-8709-1ad47211b4ad.png)
![AEB4597C-CC25-4406-AE31-C7099D6F8CA7](https://user-images.githubusercontent.com/65918663/97422381-d7531300-1961-11eb-9eaf-60f7ad3cc8ec.png)

**Comment by bwp91** [comment]
Hi @WayneKP, I'm glad you got this fixed. Thanks for your input @vsidlu. There was indeed an issue where the contact sensor would not be removed if changing the maker's type to `garageDoor`. This has been fixed in v2.1.1.

@wallacepost, please update to v2.1.1. You will be able to use the plugin settings screen to change your Maker from a switch to a garage door. You'll need it's serial number and you can configure this in the "Wemo Makers" section of the plugin settings.

**Comment by wallacepost** [comment]
Hi bwp91,
Thanks for getting back to me,
I just updated the v2.1.1, the hoobs is not restarting the service. I rebooted it couple times, no luck.
I’m rolling back to the older version 1.6.2

**Comment by bwp91** [comment]
> I just updated the v2.1.1, the hoobs is not restarting the service. I rebooted it couple times, no luck.

Were there any error messages in the hoobs logs?

**Comment by WayneKP** [comment]
Thanks for all the help, The homebridge UI and all the people who have created plugins, especially Wemo have done a great job and your efforts are appreciated thanks and this issue can now be closed
