### ISSUE TITLE
Node Version - is this an issue?

### ISSUE THREAD

**Issue by eddiem5** [bwp91/homebridge-platform-wemo#215]
I recently implemented this plugin and love it...  

I see this warning message on boot up - 

The plugin "homebridge-platform-wemo" requires Node version of >=14.5.0 which does not satisfy the current Node version of v12.19.0. You may need to upgrade your installation of Node.

I suspect this can be ignored but I was curious...

**Comment by bwp91** [comment]
Hi @eddiem5 

> I suspect this can be ignored but I was curious...

You're right, it can be ignored per se. The plugin will function correctly on node v12.19.0. However, node v14 is now the current recommended version and could be a good idea to think about [updating](https://github.com/bwp91/homebridge-platform-wemo/wiki/How-to-update-node).

**Comment by eddiem5** [comment]
Thank you.  Great plugin.
