### ISSUE TITLE
Device Names wrong

### ISSUE THREAD

**Issue by vowe** [bwp91/homebridge-platform-wemo#216]
Just a quick question that I cannot figure out: 

I have moved around a few switches and renamed them accordingly. If I look at the homebridge log, they still have their old names. Anything I can do about that to make the plugin refresh the names? I have no other setting besides:

    {
            "platform": "BelkinWeMo",
            "name": "Belkin Platform"
        },

**Comment by bwp91** [comment]
Hi @vowe 
When an accessory is initially added to Homebridge, it takes its name from how it is set in the Wemo app. If you then change the name in the Home app, this doesn't actually change the accessory name, it is conceptually a label you are changing. Behind the scenes, the accessory name is still the same, and this is why it appears as such in the logs.
The way forward would be for each device:

* Update the device name in the Wemo app
* Remove the device from the Homebridge cache (or indeed all at one), but be aware:
  * Doing this will put the accessory back in the HomeKit default room, and remove it from any automations/scenes
* The device will then be readded once Homebridge restarts, with the name you set from the wemo app

Hope this helps

**Comment by vowe** [comment]
Thank you. I did change the name in the Wemo app so I was just confused in the homebridge log.

What I did was remove the plugin, restart homebridge which removed the devices from the cache and then reinstalled the plugin. Of course that meant I had to reconfigure them in Homekit. It was only 6 devices so I could manage.

What I was looking for is a way to have the plugin refresh the names from the Wemo config so that the log matches the Wemo names, not the Homekit labels.

**Comment by bwp91** [comment]
> What I did was remove the plugin, restart homebridge which removed the devices from the cache and then reinstalled the plugin. Of course that meant I had to reconfigure them in Homekit. It was only 6 devices so I could manage.

I assume this worked? Everything in sync now? 👍

**Comment by vowe** [comment]
Yes, of course. Clean slate. I should have said that. Thank you.

**Comment by bwp91** [comment]
Excellent! I'll get this issue closed.
