### ISSUE TITLE
Wemo WiFi Smart Plug Not Being Discovered

### ISSUE THREAD

**Issue by SMJ0724** [bwp91/homebridge-platform-wemo#217]
### What issue do you have? Please be as thorough and explicit as possible.
I just purchased two of the WiFi Smart Plugs (the new ones that are smaller than the Wemo Mini Smart Plug), and got them connected to my network, however they are not being discovered by the plugin. I have attempted adding the IP addresses (in the format of "http://192.168.1.115:49153/setup.xml" and the devices are not discovered, error generated in the log is included below. It's important to note that when visiting this URL in a browser, I am unable to actually see the XML file like I am for some of the other Wemo devices on my network. Is the WiFi Smart Plug not compatible?

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.1.6

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
2.5.0

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
WiFi Smart Plug

### Please paste any relevant logs below.

```
[28/11/2020, 13:33:32] [Belkin WeMo] An error occurred loading a device - Error: connect ECONNREFUSED 192.168.1.115:49153
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.115',
  port: 49153,
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}.
[28/11/2020, 13:33:32] [Belkin WeMo] An error occurred loading a device - Error: connect ECONNREFUSED 192.168.1.116:49153
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.116',
  port: 49153,
  config: [Object],
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
```

**Comment by bwp91** [comment]
Hi @SMJ0724 
It could genuinely be that these newer smart plugs don't support the network control, especially if you are not seeing the xml file when visiting the url directly.
I don't have this device so I can't really offer much more help.
Is the device firmware up to date? Also, don't they natively support HomeKit?

**Comment by SMJ0724** [comment]
It does have native support, but it’s terrible! Belkin was completely out of the Wemo Minis that I have around the rest of the house on their Black Friday sale, so I figured I’d try the new ones out, but I think they’ll be going back.

**Comment by bwp91** [comment]
Ah. I hope you manage to source some belkin ones that will work. I’ll add it to the docs that these models aren’t supported. I’m afraid that’s all i can really do 😅

**Comment by SMJ0724** [comment]
Actually, I figured it out! Did a quick port scan and discovered that for this hardware version, they changed the port that the XML file is served from 49153 to 49152. While the autodiscover doesn't work, you can manually add these devices using http://IPHERE:49152/setup.xml. I did this, and it is working like a charm!

**Comment by bwp91** [comment]
Oh!
Could I message you on the [Homebridge Discord](https://discord.gg/7X36mdw)?
Ideally i’d like to get some more info about the device.
My username on there is bwp91

**Comment by bwp91** [comment]
@SMJ0724 If you visit the xml file of your wifi smart plug, could you copy and paste this part? (this example if is from my wemo outlet (the big one!)

```
<manufacturer>Belkin International Inc.</manufacturer>
<manufacturerURL>http://www.belkin.com</manufacturerURL>
<modelDescription>Belkin Plugin Socket 1.0</modelDescription>
<modelName>Socket</modelName>
<modelNumber>1.0</modelNumber>
<modelURL>http://www.belkin.com/plugin/</modelURL>
```

**Comment by SMJ0724** [comment]
Sorry! Just saw this now! I will send over that part of the XML once I get home.

**Comment by SMJ0724** [comment]
Also: Added you on Discord. smj0724 here.

**Comment by SMJ0724** [comment]
Sorry for the delay - it's been a week!

`<modelName>Socket</modelName>
<modelNumber>1.0</modelNumber>
<modelURL>http://www.belkin.com/plugin/</modelURL>
<manufacturer>Belkin International Inc.</manufacturer>
<manufacturerURL>http://www.belkin.com</manufacturerURL>
<modelDescription>Belkin Plugin Socket 1.0</modelDescription>`

**Comment by billchase2** [comment]
> Actually, I figured it out! Did a quick port scan and discovered that for this hardware version, they changed the port that the XML file is served from 49153 to 49152. While the autodiscover doesn't work, you can manually add these devices using http://IPHERE:49152/setup.xml. I did this, and it is working like a charm!

Thank you!! I couldn't figure out what was wrong and this did the trick.
