### ISSUE TITLE
Wemo Heater Temp Set Wrong

### ISSUE THREAD

**Issue by Emotive9** [bwp91/homebridge-platform-wemo#218]
### What issue do you have? Please be as thorough and explicit as possible.
When a Wemo heater is turned on through HomeKit the last heating temperature is not remembered. It will show at set to 84 degrees through HomeKit but the heater itself will show at 40 degrees when switched on. Setting the temperature manually after turning on will show as correct in HomeKit and on the heater.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
3.2.10

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
2.5.0

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo Heater

**Comment by bwp91** [comment]
Hi @Emotive9 
I have published a test version of the plugin which will request the 'current heating temperature' from the heater when it is turned on via the Home app. This should then be reflected on the Home app thermostat-style display.
If you're happy to give it a try, please [follow this guide](https://github.com/bwp91/homebridge-platform-wemo/wiki/Beta-Version#hoobs) to install this test version, and it should update the plugin to v2.5.1-5.
This solution may or may not work as I don't own the Wemo Heater so it's more trial and error!
Your feedback would be great.
Thanks

**Comment by bwp91** [comment]
Very close to a working fix now. This one has proven complicated due to the way the device works!

**Comment by bwp91** [comment]
@Emotive9 could I message you on the [Homebridge Discord](https://discord.gg/kqNCe2D)?

**Comment by bwp91** [comment]
I believe this issue has now been fixed in v2.7.0. I don't own this device to confirm, so I will leave this issue open for a few days for any feedback.

**Comment by Emotive9** [comment]
Hi, just tested and still defaults to 84 degrees.

**Comment by bwp91** [comment]
So when you turn on the heater through the app home it still shows as 16 degrees rather than the temperature it was previous?

**Comment by Emotive9** [comment]
Yes. If I turn it on via the WeMo app or using the front power button it will remember the previous settings. I am not sure if the "On" modes have anything to do with it. The heater has Frost Protect, Eco, Low, High.

**Comment by bwp91** [comment]
@Emotive9 not sure if you've received my message on discord, but please try the latest beta of the plugin
