### ISSUE TITLE
After latest update Wemo devices no longer appearing

### ISSUE THREAD

**Issue by robboz4** [bwp91/homebridge-platform-wemo#221]
### What issue do you have? Please be as thorough and explicit as possible.

I upgraded homebridge, config-uc, Hue and Wemo plugin. Everything is fine expect no Wemo devices. I added them in manually and they still do not show up.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
config-ui
homebridge-config-ui-x v4.36.0
Homebridge v1.2.4
* Which version of Homebridge/HOOBS do you have?

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?

homebridge-platform-wemo v2.6.1

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
mini wifi plug 
light switch ( Large version)

All work fine and show up in the Demo App on IOS.
All  show up with correct IP address on an LAN/Scan

### Please paste any relevant logs below.

Log entry : [12/8/2020, 4:32:49 PM] [Wemo] Initializing BelkinWeMo platform...

config entry:

{
            "name": "Wemo",
            "debug": false,
            "disableDiscovery": false,
            "discoveryInterval": 30,
            "disableDeviceLogging": false,
            "disablePlugin": false,
            "noMotionTimer": 60,
            "doorOpenTimer": 20,
            "manualDevices": [
                "http:/192.168.1.23:49153/setup.xml",
                "http:/192.168.1.15:49153/setup.xml"
            ],
            "makerTypes": [
                {
                    "makerTimer": 20
                }
            ],
            "platform": "BelkinWeMo"
        }

**Comment by robboz4** [comment]
Now I'm getting this message in the log files when I turned on debug:

[12/8/2020, 5:29:06 PM] [Wemo] An error occurred loading a device - Error: Request failed with status code 404
    at createError (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}.

**Comment by bwp91** [comment]
Hi, in your manual devices you need two forward slashes after the `http:`
Please try this!

**Comment by robboz4** [comment]
Thanks! That seems to have fixed. Sorry I missed the double”//“. My bad!
