### ISSUE TITLE
Last Changed Characteristic

### ISSUE THREAD

**Issue by fleiscpj** [bwp91/homebridge-platform-wemo#222]
* **Please explain your feature request in a one or two sentences.**
I’d like to have the ability to see last state elapsed time in minutes. This would allow an automation to be created in Home Controller app to allow something to happen after the specified amount of time of a switch being activated. Like shutting off the TV 15 minutes after the lights are shutoff, etc. 

* **Is your feature request related to a problem? Please describe.**

* **Any particular Wemo devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Would this not be an ideal situation for:
https://www.npmjs.com/package/homebridge-delay-switch
I don’t see how it’s even possible to show the “time elapsed” in the home app?

**Comment by bwp91** [comment]
And actually this is possible in the Home app already by creating an automation, choosing the trigger accessory then "Convert to Shortcut" where you can add "wait" delays.
