### ISSUE TITLE
Support for Wemo Outdoor Plug

### ISSUE THREAD

**Issue by bonneau** [bwp91/homebridge-platform-wemo#225]
* **Please explain your feature request in a one or two sentences.**
Was curious if you could add support for the Wemo Outdoor Plug (https://www.belkin.com/us/p/P-WSP090/).

* **Is your feature request related to a problem? Please describe.**

* **Any particular Wemo devices that this relates to?**
Wemo Outdoor Plug (https://www.belkin.com/us/p/P-WSP090/)

* **Anything else?**
This is a great plugin! Thanks for taking the time to build it. It's a huge upgrade from the broken Wemo Bridge. :)

**Comment by bwp91** [comment]
Hi @bonneau 
Would you be able to message me on my [discord](https://discord.gg/cMGhNtZ3tW) with regards to implementing this new device?
thanks and happy new year!
