### ISSUE TITLE
Support for Wemo/Holmes air purifier

### ISSUE THREAD

**Issue by krharrison1** [bwp91/homebridge-platform-wemo#226]
I have one of these and would like to see it added as a supported device. Willing to help with testing etc.

**Comment by bwp91** [comment]
Hi @krharrison1 
Would you be able to message me on my [discord](https://discord.gg/cMGhNtZ3tW) with regards to implementing this new device? It requires a lot of back and forth messaging so it's much simpler there!
thanks and happy new year!
