### ISSUE TITLE
Devices in separate VLAN

### ISSUE THREAD

**Issue by danremollino** [bwp91/homebridge-platform-wemo#227]
• Homebridge v1.2.5 using Homebridge UI v4.36.0 on an RPi 4b+
• Node v 14.15.3
• npm v6.14.10
• homebridge-platform-wemo v2.8.0
• all devices are set up manually, UPnP is turned off
• all dimmers report as v1 hardware, but are the updated model with the all white design

I have used this plugin in the past without issue, but stopped using it for a few months to try out the Wemo native HomeKit support to see if it got any better. After finding out what a giant mess that still is, I re-set up this plugin to a new home bridge install.

My Home app becomes out of sync in a pretty erratic manor. I think I have what's going on figured out, but depending on how things are changed the outcome is different...

1. Making a change in the Home app works as expected.

2. Making a Siri request: 
    • Making an on/off request seems to work as expected. The Home app status turns to on or off properly.
    • Making a brightness change will always display the previous status, not the one just requested. So if the dimmer started at 100% and I make a request to turn it to 50%, the status visibly turns to 50% for a millisecond and then back to 100%. If I then make a second request to turn to 75%, the status will then show the previous 50%. This continues this way. To be clear, the actual brightness of the light is correct, but only the status is behind.

3. Making and change at the device does not update in the Home app at all. Both on/off and brightness changes are never reflected in my Home app.

Thank you and let me know if you need more information.

**Comment by bwp91** [comment]
Hi @danremollino 
Thanks for the detailed issue.
I don't personally own the dimmer so would need your assistance with troubleshooting this.
Any chance we could message on my discord?
https://discord.gg/cMGhNtZ3tW
Thanks!

**Comment by bwp91** [comment]
The issue here seemed to be that the devices were in a separate VLAN to the Homebridge instance.

I have updated the title accordingly for easier future reference.

The issue has been resolved by enabling wifi on the homebridge device and giving it an IP from the VLAN where the wemo devices were located.

**Comment by elkaboing** [comment]
I came here to find some additional information on VLANs. My Mac mini is running Homebridge connected to my management VLAN via ethernet. To get around the issue of homebridge running on a separate VLAN from the IOT devices, I  followed the information outlined in [issue #220](https://github.com/bwp91/homebridge-platform-wemo/issues/220) and manually configured the IP addresses in the homebridge-wemo configuration files following the format: http://192.168.20.136:49153/setup.xml.

Problem is, it seems the wemo devices are changing the port they listen on which occasionally breaks the connection with homebridge. 

Is there any additional configuration needed when setting-up a second interface? I've read that the default action is to listen on all interfaces so the "listen_interface" option shouldn't be necessary? 

Thanks for your work on this plugin, as stated above the native Wemo HomeKit integration is a complete mess.

**Comment by danremollino** [comment]
@elkaboing The devices are going to change ports, usually when they are rebooted. There's nothing you can about this other than constantly update your config when they change. You have to switch back to auto discovery, it's the only way to not give yourself a headache.

To get Homebridge to work reliably with VLANs you have to have the device running Homebridge to have an ip from your IoT VLAN. I've not been able to get a 100% reliable set-up without doing this yet. I'm using an RPi, but it should be no different for your Mac mini. If you want the Mac mini on both networks, you can:

1. Give your Mac mini a static address on the management VLAN via ethernet. (you are probably set this way, currently)
2. Give your Mac mini a static address on the IoT VLAN via Wi-Fi. Alternatively, you should be able to make a Virtual Interface in System Preferences > Network to get an address only using ethernet.
3. Make sure your firewall is not blocking Homebridge/Homekit traffic between networks. I would temporarily disable the firewall between the networks if possible to confirm everything is working, and then play with the settings after to make it easier to troubleshoot.

Once you have a working address from both networks, you should be able to access Homebridge from both. If you have having issues, you may want to try out Homebridge 1.3b. If you use it and Homebridge UI there is a new setting to view which network interfaces Homebridge is listening on. It *should* automaticity work, though.

Since having this setup my Homebridge is finally working reliably.

**Comment by elkaboing** [comment]
@danremollino  - thanks for the info. I just dug out an old thunderbolt to ethernet adapter and set it up just as you described. I removed the manual devices block from my wemo config, restarted and all my devices were initialized without issue. 

I wish I would have done this last week, was much quicker than the time it took to enter all the IP addresses of my 29 Wemo devices into the config file and also in my web browser to check which port to use - not knowing the port was going to change at some point.

Firewall rules are solid as well.

Thanks again

**Comment by bwp91** [comment]
Thanks for your input here @danremollino kudos to you for finding a solution to this :) I have updated the readme with a note regarding this.

I'd just like to point out

>  If you have having issues, you may want to try out Homebridge 1.3b. If you use it and Homebridge UI there is a new setting to view which network interfaces Homebridge is listening on. It should automatically work, though.

The Homebridge settings should have nothing to do with this plugin. The "listener interface" for this wemo plugin can be configured via the `wemoClient.listen_interface` option. [Link to config wiki page for reference](https://github.com/bwp91/homebridge-platform-wemo/wiki/Configuration-(v2.0)#optional-settings). It's a string of interfaces that the plugin will use to listen for device updates, and if blank (and not specifically configured) it will use all interfaces.

Ben
