### ISSUE TITLE
[Wemo Light Switch 3-Way] still pending discovery, will retry connection.]

### ISSUE THREAD

**Issue by Tesla-P100FX** [bwp91/homebridge-platform-wemo#228]
I had a switch installed with a older version of you plug in that required log in credentials for Wemo.  I had a light switched installed that i removed and It does not show up in my WEMO app, and support says it does not show up in my cloud configuration.   Despite that i get this message all the time
[Wemo Light Switch 3-Way] still pending discovery, will retry connection.] 

I am running HOOBS Version | 3.3.1 Node Version | 12.16.3

My Hoobs server is a Raspberry Pi 

My Wemo Plug in is 2.8.1 published 1/7/2021 • 2 days ago and the issue predated this update 

 {
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            },
            "name": "Wemo"
        }

I looked at a number of JSON files on my PI but can not find a mention of this device to delete.

**Comment by bwp91** [comment]
Hi @Tesla-P100FX 
Due to how the plugin currently works with removing devices, your situation (with not having the device anymore) is going to be a bit fiddly.
Any chance we could message on my discord server?
https://discord.gg/cMGhNtZ3tW
Thanks

**Comment by bwp91** [comment]
Gonna mark this issue as complete since this particular problem is resolved.

In the next release there will be a new configuration option to remove such orphaned devices.

Thanks!
