### ISSUE TITLE
Ignored Devices not Saving

### ISSUE THREAD

**Issue by egregious87** [bwp91/homebridge-platform-wemo#230]
### What issue do you have? Please be as thorough and explicit as possible.
With the new version that came out today (2.9.0) a new wemo device was found and added into homekit. This device is already in homekit as its homekit compatible out of the box (Wemo WiFi Smart Plug). I'm trying to hide this duplicate device since I'm now seeing two of the same device (one from built in homekit compatibility and one from the wemo plug-in you very nicely developed)

I tried to use the Ignored Devices section in the configuration screen along with adding it manually in the advanced section, but my request to ignore that devices is being ignored. I thought maybe because the serial number doesn't start with a 22 was the reason for the device to not be ignored, so I added another device that serial number does start with 22 but that would still show up in the logs/homekit app. I'm not sure what else to do at this point. Any assistance in fixing this would be greatly appreciated!

I also tried to unplug the Wemo WiFi Smart Plug, have the other devices be found and added, then tell the Discovery Interval be set to 0 or Disable Discovery to stop it from looking for new devices, but when I do this the existing devices it already found can't found in the logs anymore and stop working in the Home app. 

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
(3) HOOBS

* Which version of Homebridge/HOOBS do you have?
3.3.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 4 Model B Rev 1.1
Node Version: 12.16.3

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
2.9.0, this was not an issue on the previous version.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo WiFi Smart Plug (Model: WSP080)

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @egregious87 

Are you using the correct format for the devices to ignore config entry? For HOOBS, you need to enter in the "Ignored Devices" box in this format:

```
[
   "22************"
]
```

Obviously changing the above entry with the serial number you wish to ignore. So long at it is the serial number, the fact it doesn't start with `22` doesn't matter.

Thanks

**Comment by egregious87** [comment]
Ah I understand what your notes were showing now, I just thought it had to be in the brackets like this ["22************"].

This might have done the trick, thank you for clarifying! 

Am I able to set the Discovery Interval to zero and my current devices can still work? If not what interval would you suggest as I don't need it to check unless I add a new device.

Thanks for the fast response!

**Comment by bwp91** [comment]
```
["22************"]
```

will work in exactly the same way as this

```
[
   "22************"
]
```

but the main thing is have you managed to get the plugin to ignore the device?

> Am I able to set the Discovery Interval to zero and my current devices can still work? If not what interval would you suggest as I don't need it to check unless I add a new device.

Do you have your devices setup manually via the config or are they automatically discovered? If they are automatically discovered then I would recommend keeping the discovery interval on.
