### ISSUE TITLE
Error loading device ... - read ECONNRESET

### ISSUE THREAD

**Issue by permaMonk** [bwp91/homebridge-platform-wemo#231]
Something similar to #223

...
[Belkin WeMo] [Waschmaschine] initialised with s/n xxx and mac address yyy.
[Belkin WeMo] [Waschmaschine] updating current consumption to [0W].
[Belkin WeMo] [Waschmaschine] updating total consumption [0.005 kWh].
[Belkin WeMo] [Gästezimmer Stehlampe] setting state to [on].
[Belkin WeMo] [Gästezimmer Stehlampe] setting state to [off].
[Belkin WeMo] [Waschmaschine] updating total on-time [0 hours].
[Belkin WeMo] [Waschmaschine] updating total consumption [0.006 kWh].
[Belkin WeMo] Error loading device [http://192.168.87.26:49153/setup.xml] - read ECONNRESET.
[Belkin WeMo] Error loading device [http://192.168.87.26:49153/setup.xml] - read ECONNRESET.
[Belkin WeMo] Error loading device [http://192.168.87.26:49153/setup.xml] - read ECONNRESET.
...

It starts normally - everything is fine. Then after a few minutes only "error loading device" lines appear. And this only with a Wemo Insight Switch. The other one of 2 devices is a Wemo Switch. No firmware change made. Port change to 49154 or 49152 did not helped. All IP addresses are fixed. The Wemo Insight Switch is connected cause I can manage it with the original WEMO app. Is there a problem with Wemo Insight Switches?

My config:
{
"name": "Belkin WeMo",
"manualDevices": [
"http://192.168.87.25:49153/setup.xml",
"http://192.168.87.26:49153/setup.xml"
],
"platform": "BelkinWeMo"
},

--

Just found out in the log:
[Belkin WeMo] Plugin [v2.9.0] initialised. Setting up device discovery...
[Belkin WeMo] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
[Belkin WeMo] [Gästezimmer Stehlampe] initialised with s/n xxx and mac address yyy.

The 2. device Wemo Insight Switch was NOT listed. Um - why?

**Comment by bwp91** [comment]
Hi @permaMonk 

> The 2. device Wemo Insight Switch was NOT listed. Um - why?

It looks like the plugin is having trouble connecting to the Waschmaschine. 

Is there any reason why you use manualDevices over automatic discovery?

**Comment by permaMonk** [comment]
Yes there was a time before, where have been some troubles to recognize my WEMO devices. Therefor I was so lucky some time ago you added this manual configuration option. And that worked for a long time without any problems.

**Comment by bwp91** [comment]
> Would you please post an alternative config part with auto detection?

In fact I was going to suggest trying normal discovery. This can detect and work with port changes. But normal discovery often doesn't work when you have Wemo devices on a different IP network/subnet from your Homebridge instance.

Does your Homebridge instance have an IP on your 192.168.87.X range?

For auto discovery, just remove the manualDevices section, ie

```
{
"name": "Belkin WeMo",
"platform": "BelkinWeMo"
},
```

**Comment by permaMonk** [comment]
Yes, sure, now I remember I´ve had different subnets. But not anymore.

I changed the config to auto detect. Gimme a half time to watch and control the log.

**Comment by permaMonk** [comment]
It looks good. :))

But tomorrow I`ll take a second eye on it. ;)

**Comment by permaMonk** [comment]
It´s tomorrow now and everything with this plugin looks really fine.

Thanks again for your responsive and very helpful support. :)
