### ISSUE TITLE
Energy History in Eve App?

### ISSUE THREAD

**Issue by tmur11** [bwp91/homebridge-platform-wemo#232]
I cannot seem to get any energy history to show in EVE app. Should it not be?

**Comment by bwp91** [comment]
Hi @tmur11 
At the present time I believe (since I only took over this plugin recently) the following is shown in the Eve app:

* Current consumption in W
* Total consumption for the current day in kWh (this resets at midnight by the device itself)

The 'history' graph is not yet implemented, but something I can look into.

**Comment by bwp91** [comment]
In the current beta version of this plugin I have added Eve history data for Insight devices.

If you're happy to try the beta I'd be grateful for any feedback... as I don't own the insight device myself

**Comment by tmur11** [comment]
@bwp91 thanks for the update! I'll install the beta version tonight and provide you feedback.

**Comment by tmur11** [comment]
@bwp91 It appears to be working! Thank you very much. 

If only you could work your magic on the [ds18b20](https://github.com/DanTheMan827/homebridge-ds18b20) plugin for temperature history 

![21-02-02 20-52-29 4002](https://user-images.githubusercontent.com/21132832/106979020-6a52d480-672b-11eb-9bcc-d79bfb12af19.png)
![21-02-03 17-08-13 4006](https://user-images.githubusercontent.com/21132832/106979022-6b840180-672b-11eb-96a1-97b3ebfa1218.png)
![21-02-02 20-52-56 4004](https://user-images.githubusercontent.com/21132832/106979026-6cb52e80-672b-11eb-81eb-fb46098cf6fc.png)

**Comment by tmur11** [comment]
Upon further review it seems that perhaps 'Total Consumption' is not displaying correctly and only shows 0.00kWh although it seems the history is working?

![image](https://user-images.githubusercontent.com/21132832/106980518-552b7500-672e-11eb-95c1-5d54634f354b.png)


![21-02-04 21-13-41 4012](https://user-images.githubusercontent.com/21132832/106980513-5361b180-672e-11eb-89af-3b36a8d2364d.png)

**Comment by bwp91** [comment]
Hi @tmur11 

Glad to see the historical data is working at least.

The Eve app bases it's *TotalConsumption* graph data off the values of the *CurrentConsumption* that it receives regularly from the plugin.

The *TotalConsumption* value, however, needs to be calculated by the plugin (ie Eve does not use its own data to calculate this, it's totally up to the plugin). Obviously something is not working with how I have tried to implement this. I will review the code and get back to you.

**Comment by bwp91** [comment]
Could you update to the beta version of the plugin (currently 2.12.0-3) to see if this correctly shows the total consumption in Eve app?

**Comment by tmur11** [comment]
I have updated and the behavior is the same. I should clarify prior to updating to (2.12.0.-3) I did start to see numbers in my _TotalConsumption_ field in EVE. 

It seems only whole numbers appear in _TotalConsumption_ even though EVE displays 2 decimal places.

![image](https://user-images.githubusercontent.com/21132832/107126134-199ec100-687c-11eb-900c-37f030cc13c3.png)

**Comment by bwp91** [comment]
Could you try removing the accessory from the cache so it is re-added to Homebridge?
This _might_ fix the decimal point issue.
Please let me know!
