### ISSUE TITLE
Port changes - auto detect correct port

### ISSUE THREAD

**Issue by Muzach** [bwp91/homebridge-platform-wemo#234]
It looks like some of my WeMo switches (Belkin Plugin Socket 1.0) seem to change ports periodically and the plugin, configured with manual devices, stops working.

My rPi is on a different VLAN from my wemo devices, but the firewall is open for the rPI to scan the IP-range of the IOT VLAN (as well as mDNS reflectors); but the automatic discovery doesn't work.  Enhancement #1 would be to have some extra config about the IP range to scan for wemo devices and not assume they're on the same VLAN.  A CIDR notation of 192.168.0.0/16 would be the ideal way to express which IP ranges to discover.  Because of this limitation, I'm using the manually configured devices.

My workaround is to figure out the new port (49153, 49154, 49155) and edit the homebridge configuration.  I then realized I can add all the ports as manual devices and then the logs spew errors for the ports not in use.  

What would be better is if I can leave out the port in the manual config and the plugin can try the 5 permutations to find the device on the static IP.

**Comment by bwp91** [comment]
Hi @Muzach 
Are you able to give your rPi an IP on the vlan where your wemo devices are? For example using wireless if your pi is already connected via ethernet to (i assume) your main lan.
Other users have had success with auto discovery using this method which in turn fixes the port changing problem.

**Comment by Muzach** [comment]
I’d rather not change the security profile of my rPI just to get the scanner to work.  The wemo are visible from the rPI if I could get some knobs exposed to target the scanner to the right IP range.  If the scanner could simply be told the IP range to scan that would do it, or a hybrid manual mode where I provide the IP but not the port would also be great.

**Comment by bwp91** [comment]
@Muzach could I message you on my discord server?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
For anyone following this issue, in the current beta of the plugin I have added a feature to auto detect the port of manual devices.

**Comment by Muzach** [comment]
Tested build 2.9.2-9 and it's working great across vlan boundaries.  Thanks!
