### ISSUE TITLE
WeMo Plugin Failure

### ISSUE THREAD

**Issue by wnaylor** [bwp91/homebridge-platform-wemo#236]
### What issue do you have? Please be as thorough and explicit as possible.
**My WeMo plugin doesn’t work anymore. At the beginning of February after I updated the plugin none of my devices work. The work in the WeMo app and Alexa and Google but not in HomeKit.**

### Details of your setup.
**I have Hoobs Core version 3.3.2 on a Raspberry Pi 4B.**

* Which version of Homebridge/HOOBS do you have?
**Version 3.3.2**

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
**Raspberry Pi4B**

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
**Platform Wemo version 2.11.0**

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
F7C059, F7C030, F7C029 (Wemo Dimmer, Wemo Smart Light Switch, Wemo Insight Outlet)

### Please paste any relevant logs below.

{
            "platform": "BelkinWeMo",
            "plugin_map": {
                "plugin_name": "homebridge-platform-wemo"
            },
            "name": "Wemo",
            "debug": false,
            "discoveryInterval": 15,
            "disablePlugin": false,
            "mode": "auto"
        }
[logs 2:5:2021.txt](https://github.com/bwp91/homebridge-platform-wemo/files/5933727/logs.2.5.2021.txt)

```

```

**Comment by bwp91** [comment]
Hi, have you changed any firewall/router/network settings? 

Do you remember which version of the plugin you were running when it was working before you updated?

**Comment by wnaylor** [comment]
My router went down and I had to reset it but my network settings are the same except for my computer IP. The Hoobs system IP remains the same. I do not have any firewall set. I do have Bitdefender operational but the settings haven't changed and I do not know what version of the Wemo plugin I was running before I will say that it had to be the version just before 2.11.0. Again my Wemo app and Alexa and Google can still interact with these devices. I can log into my Wemo hub through the web and it shows that my devices are all online. I have included a log from my Wemo plugin in via the URL given in the Hoobs log. Thank you for your support.

[wemo_bridge_log_202102041320.txt](https://github.com/bwp91/homebridge-platform-wemo/files/5934114/wemo_bridge_log_202102041320.txt)

**Comment by bwp91** [comment]
Humour me here please just try disabling bitdefender and restarting HOOBS to see if this changes anything?

**Comment by wnaylor** [comment]
Ben,

I did as you requested but I am getting the same errors. Is there a Wayne I can go back to an earlier plugin?

Wayne

**Comment by bwp91** [comment]
Yes, when using HOOBS you should:

* Stop the hoobs service
* Run these commands in the HOOBS UI terminal one after another, changing the X.Y.Z to the version you wish to install
  * `cd ~/.hoobs/`
  * `npm install homebridge-platform-wemo@X.Y.Z`
* Start HOOBS again

I would be interested to hear if a (and which) previous version fixes your issues, so I can look into any changes between versions that may be causing them.

Thanks

**Comment by wnaylor** [comment]
Ben,

After installing demo version 2.1.1 and leaving it alone for a few hours, I logged back into Hoobs and all my demo devices are now working. I enclosed below the demo part of the logs. I am not going to update the wemo app at this time.

Thank you for your continued support.

2/6/2021, 5:01:41 PM [Wemo] [WeMo Basement] setting state to [off].
2/6/2021, 5:01:41 PM [Wemo] [WeMo Basement] setting outlet-in-use to [no].
2/6/2021, 5:01:41 PM [Wemo] [WeMo Basement] setting consumption to [0W].
2/6/2021, 5:01:42 PM [Wemo] [WeMo Basement] setting state to [on].
2/6/2021, 5:01:42 PM [Wemo] [WeMo Basement] updating state [off].
2/6/2021, 5:01:43 PM [Wemo] [WeMo Basement] updating state [on].
2/6/2021, 5:01:44 PM [Wemo] [Computer Light] setting state to [off].
2/6/2021, 5:01:45 PM [Wemo] [Computer Light] setting state to [on].
2/6/2021, 5:01:52 PM [Wemo] [TV Light] setting state to [on].
2/6/2021, 5:01:52 PM [Wemo] [TV Light] updating brightness to [90%].
2/6/2021, 5:01:53 PM [Wemo] [TV Light] setting state to [off].

Wayne

**Comment by wnaylor** [comment]
Thank you for your help. I did reply that I was able to re-install the WeMo plugin using version 2.1.1. I am afraid to update the plugin to the new updated version for fear that I might run into the problems I had before. Has there been anyone else with the same problem or was the problem fixed? Do you think I should go ahead and try to update the plugin and if it doesn't work properly reinstall the version that works? What do you think? Thank you again for your support.

**Comment by bwp91** [comment]
Hi @wnaylor 

I apologise I haven't gotten back to you. From what you said I thought you were planning to stay on v2.1.1.

I would try updating the plugin again to the latest version. If you receive the errors again I can look into this further.

Also very happy to message you on Discord - it could be useful to message in real time when we are both online to try and troubleshoot this.

https://discord.gg/cMGhNtZ3tW

Thanks
