### ISSUE TITLE
Error in logs for a wemo Wi-Fi smart plug

### ISSUE THREAD

**Issue by BrianS42** [bwp91/homebridge-platform-wemo#237]
### What issue do you have? Please be as thorough and explicit as possible.
In the log file, I keep getting this error (but it does not crash, it just fills up the logs).  It happens every 2 - 2.5 minutes and is only for the Wi-Fi smart plug that I just got.  I put the serial number in the ignored devices (as homekit picks it up automatically), but since it starts with M1 instead of 22, I'm not sure if it is actually honoring that ignored device:
[2/13/2021, 1:30:54 PM] [WeMo Platform] [http://192.168.4.125:49152/setup.xml] connection error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20).

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
Homebridge + config-ui (although I was using homebridge CLI before and got the same results)

* Which version of Homebridge/HOOBS do you have?
1.1.7

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
I run on a MacOS - Node v 14.15.5 and NPM v 6.14.11

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
I am on v 2.12 - I just upgraded today, but it happened on the previous version too.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wi-Fi smart plug: WSP080

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @BrianS42 

In the plugin-ui in the "My Devices" tab, does the device appear in this list?

**Comment by BrianS42** [comment]
No, it does not show up in there.

**Comment by bwp91** [comment]
What is the format of the serial number of the device? Is it just numbers and capital letters?

Also, if you remove it from the ignored devices, does the device add to Homebridge with no further errors in the logs?

**Comment by BrianS42** [comment]
The serial is all numbers and capital letters.

I removed it from the ignored devices and the error seems to have gone away.  Although the Wemo outlet now seems to crash (stops getting recognized by homebridge and the Wemo app until I unplug it and plug it back in).  Not sure if it is related to this or not.  I’ll try to re-add it and see if it is more stable.

**Comment by BrianS42** [comment]
I just reset the plug entirely (with Wemo support) and re-set it up.  It is no longer hanging (at least so far), but I did notice that even with the SN removed from the config file, it is still showing the error (I saw the error when homebridge initialized this time) right next to it finding the device.  I’ll leave it off the ignored list and see if the error keeps presenting itself.

**Comment by BrianS42** [comment]
Update, I haven’t seen the error for about 3 hours.  But I do have the Wemo device in my HomeKit twice (once in homebridge and once natively with HomeKit).

**Comment by bwp91** [comment]
Any luck if you now add the serial number back to the ignore list? Please be sure to use the plugin setting ui to add the serial number, so it adds in the correct format to the raw json config file.

**Comment by BrianS42** [comment]
I just added it back.  I have been using the UI to update the serial.  After adding it back now  I just restarted and no error so far.  I'll keep an eye on it.  But it is displaying right in homekit.  Just for reference, here is the config.json section in case I'm doing something else wrong.  I installed this a while ago, before I got the UI so it could be off:
{
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "manualDevices": [],
            "ignoredDevices": [
                "221...",
                "224...",
                "M1A..."
            ],
            "discovery": true
}

**Comment by BrianS42** [comment]
Update.  I still see these errors in the log and ranges every 30 seconds to about 3 minutes.  But it functions fine.  So not a huge issue, but wanted to see if this was a common error with they type of connector.

**Comment by bwp91** [comment]
Your config looks fine. In fact your `manualDevices` and `discovery` options are redundant so for good housekeeping you could remove them.

With regards to the logging, no, it shouldn't be the case that you repeatedly get these messages, especially for a device you ignore. 

I've made a small change in a beta version of the plugin I have just released, could you update to it to see if it has made any improvements?

The version you'll need is v2.13.1-0.

**Comment by BrianS42** [comment]
I didn't see v2.13.1-0 but saw v2.13.1-1 and installed that just now.   I'll monitor and report back.  Thanks!

**Comment by BrianS42** [comment]
Looking good right now.  Earlier today I when I rebooted I got 25 errors in 1 hour.  I still haven't seen any errors since rebooting.

**Comment by bwp91** [comment]
Ah this is good news :)
