### ISSUE TITLE
Wemo Insight shows as multiple devices

### ISSUE THREAD

**Issue by picnicbob** [bwp91/homebridge-platform-wemo#239]
### What issue do you have? Please be as thorough and explicit as possible.
My Wemo insight switch shows as 2 tiles in the Home app since the latest update.

### Details of your setup.
Homebridge (CLI)
{
            "name": "WeMo Platform",
            "mode": "auto",
            "platform": "BelkinWeMo"
}

* Which version of Homebridge/HOOBS do you have?
Homebridge 1.1.7

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi4, Node v12.20.2

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
The issue is new since I updated to v2.12.0, but I'm not sure what I was using before it.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo Insight firmware 2.12

**Comment by bwp91** [comment]
Hi @picnicbob 
Could you grab me a screenshot of both tiles (i'm looking to see the accessory type).
Also, please confirm whether both accessories show 2.12 as the firmware from the home app.
Thanks

**Comment by picnicbob** [comment]
![IMG_0550](https://user-images.githubusercontent.com/1394696/108071766-1fdb2d00-7034-11eb-8f69-a73357966e90.PNG)
![IMG_0548](https://user-images.githubusercontent.com/1394696/108071768-2073c380-7034-11eb-8200-5e7b945b8604.PNG)
![IMG_0549](https://user-images.githubusercontent.com/1394696/108071770-2073c380-7034-11eb-8ba5-333ed3658d31.PNG)

**Comment by picnicbob** [comment]
They're both appearing as Outlets (even though one shows as a light)

**Comment by bwp91** [comment]
Would you be able to update the plugin to the latest beta version and then remove the accessory/ies from the cache to see if this sorts out this problem?

To save resetting the whole cache (if you use CLI) you can use a either of these plugin settings to remove a single accessory from the cache:

* `"removeByName": "accessory name as appears in logs"`
* `"ignoredDevices": ["serial number of device"]`

After restarting Homebridge:

* the first option will remove the accessory when Homebridge starts again, and the accessory will be added again straight away when the plugin discovers it
* the second option will remove the accessory when Homebridge starts again, but will **not** add the accessory until you remove the serial number from the config and restart Homebridge again

Remember to update to the beta first if you're happy to do so!

**Comment by picnicbob** [comment]
Well, I cleared my Homebridge accessories cache and the outlet is showing up as a single tile again. Now I've got to reconfigure everything else in homebridge... Not sure what went wrong there but it definitely coincided with the wemo 2.12 update.

**Comment by bwp91** [comment]
Glad it's gone back to one tile as it should be. Will close this issue now but please do get in contact again if it happens to duplicate again!
