### ISSUE TITLE
Query interval?

### ISSUE THREAD

**Issue by permaMonk** [bwp91/homebridge-platform-wemo#240]
It´s about a Wemo Insight.

At the moment I can see in the log that there is an irregular query interval for the consumption values between 1 - 8 seconds. This is not necessary for my requirements.

Question: Can this be precisely defined via the config settings? Every 30 seconds or every minute?

**Comment by bwp91** [comment]
Hi @permaMonk 

The plugin doesn’t query for updates for the insight. the device itself sends updates as and when it feels it needs to. and the plugin receives each of these updates and logs/updates accordingly. 

i have added an option recently to ignore an update if the difference between the new wattage and the previous is less than a certain amount. Perhaps this could be used to make the log entries less frequent?

**Comment by permaMonk** [comment]
Yes I know about this feature and I use it. :)
So, too bad, then my desired feature does not work.

**Comment by bwp91** [comment]
I could perhaps look into a way of limiting the wattage entries on a time basis eg don't log if an update has already been received in the past 30 seconds.

But in this case it would still not be **exactly** every 30 seconds, the entries would be at least 30 seconds apart.

Not sure if this could be a useful option?

**Comment by permaMonk** [comment]
Really appreciate your thoughts.

Yes maybe a way.

My main intention is not to clutter the log to much with to many entries of the Wemo plugin. And to factor in the HB have to much work in the future when I have installed 20 more plugins. ;)

**Comment by bwp91** [comment]
You can try the latest beta I have just pushed. You should be able to set a 'timeout' for wattage logs via the plugin settings.

Unfortunately today my raspberry pi has died somehow so unable to test myself.

**Comment by permaMonk** [comment]
Sure. But I need (again, sorry) the precise command how to install the beta.

—

**Comment by permaMonk** [comment]
sudo npm install homebridge-platform-wemo@beta -g

Correct?

Am Sa., 6. März 2021 um 16:34 Uhr schrieb Ben <notifications@github.com>:

**Comment by bwp91** [comment]
Are you running Homebridge UI? HOOBS? The command depends on the platform

**Comment by permaMonk** [comment]
Ok 2 fields with the name "Wattage Logging". Should be named a little bit
different. :)

Set the time at 30 sec.

Config:
{
    "name": "Belkin WeMo",
    "mode": "auto",
    "wemoInsights": [
        {
            "serialNumber": "221540K12002B3",
            "wattDiff": 2,
            "timeDiff": 30
        }
    ],
    "platform": "BelkinWeMo"
}

Have to wait a little. Washing machine has some rest until tomorrow. I'll
tell you something about it tomorrow.

Am Sa., 6. März 2021 um 16:34 Uhr schrieb Ben <notifications@github.com>:

**Comment by permaMonk** [comment]
Hi Ben.

It work. :)

[08/03/2021, 16:20:14] [Belkin WeMo] [Waschmaschine] updating current
consumption to [176W].
[08/03/2021, 16:20:52] [Belkin WeMo] [Waschmaschine] updating current
consumption to [85W].
[08/03/2021, 16:21:24] [Belkin WeMo] [Waschmaschine] updating current
consumption to [55W].
[08/03/2021, 16:21:54] [Belkin WeMo] [Waschmaschine] updating current
consumption to [46W].

Am Sa., 6. März 2021 um 16:34 Uhr schrieb Ben <notifications@github.com>:
