### ISSUE TITLE
How to remove a non existing device

### ISSUE THREAD

**Issue by Schattenkaiser** [bwp91/homebridge-platform-wemo#241]
### What issue do you have? Please be as thorough and explicit as possible.
Wemo plugin trying to start a non existing device (from my past wwemo configuration). An error occurs, saying: [Wemo] [EG Bad] device appears to be offline.
after that the homebridge service stopps working with the following messages
Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Got SIGTERM, shutting down Bridge...

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
3 - Hoobs

* Which version of Homebridge/HOOBS do you have?
3.3.3

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry P4 8GB
node version 14.16.0

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
2.14.0 veröffentlicht 3/2/2021 • 4 days ago

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Lightbulb formerly named 'EG Bad' but this device is no longer exisiting

### Please paste any relevant logs below.

```
6.3.2021, 10:23:38 [Wemo] [uuid:Bridge-1_0-231448B01004D8] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<StatusChange></StatusChange>
</e:property>
<e:property>
<SubDeviceFWUpdateStatus></SubDeviceFWUpdateStatus>
</e:property>
</e:propertyset>


6.3.2021, 10:23:38 [Wemo] [uuid:Bridge-1_0-231448B01004D8] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<TimeSyncRequest>0</TimeSyncRequest>
</e:property>
</e:propertyset>


6.3.2021, 10:23:38 [Wemo] [uuid:Bridge-1_0-231448B01004D8] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<TimeZoneNotification>005</TimeZoneNotification>
</e:property>
</e:propertyset>


6.3.2021, 10:23:38 [Wemo] [Gartenlicht Garage] initialising with options {"disableDeviceLogging":false}.
6.3.2021, 10:23:38 [Wemo] [Gartenlicht Garage] initial subscription for service [urn:Belkin:service:basicevent:1].
6.3.2021, 10:23:38 [Wemo] [Gartenlicht Garage] initialised with s/n 221304K11000AD and mac address EC:1A:59:84:1E:24.
6.3.2021, 10:23:38 [Wemo] [EG Bad] device appears to be offline.
6.3.2021, 10:23:38 [Wemo] [uuid:Socket-1_0-221304K11000AD] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>0</BinaryState>
</e:property>
</e:propertyset>


6.3.2021, 10:23:38 [Wemo] [Gartenlicht Garage] received update [binaryState: 0].
6.3.2021, 10:23:42 Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
6.3.2021, 10:23:42 Got SIGTERM, shutting down Bridge...
6.3.2021, 10:23:43 [Wemo] SSDP client gracefully stopped.
6.3.2021, 10:23:43 [Wemo] SSDP client gracefully stopped.
6.3.2021, 10:23:43 [Wemo] Listener server gracefully closed.
6.3.2021, 10:23:43 [Wemo] Listener server gracefully closed.
```

**Comment by bwp91** [comment]
Hi @Schattenkaiser 
The 'EG Bad' device can be removed from HOOBS using the 'Remove By Name' plugin setting. Type in 'EG Bad'

<img width="200" alt="Screenshot 2021-03-06 at 13 13 17" src="https://user-images.githubusercontent.com/43026681/110207921-ebfa6700-7e7d-11eb-8d5f-597bccef4a71.png">

Then click on 'Save Changes' HOOBS will restart, removing the device from the accessory list.

You can then go ahead and remove the device name from the 'Remove By Name' setting and restart HOOBS.

**Comment by Schattenkaiser** [comment]
Hi @bwp91
Thanks for reply
I've restored hoobs from a backup, and setup new with only wemo plugin. 
Homebridge-service seems working again, but after installing the wemo plugin again, the excluded [EG Bad]  bulb is still to see.

I also tried the step you mentioned, but wirth the same effect. The only change is, that the susequent error is no longer showing, and hoembridge service is working again. The strange behavior is, that the Wemo-Link seems not responding (see **marked** below)
As result I can see all bulbs and switches in Hoobs, but not on my Home-App at the iPhone

![image](https://user-images.githubusercontent.com/80150829/110208598-6e882400-7e88-11eb-8a8d-323e34bdfd17.png)

'''
6.3.2021, 14:22:22 Got SIGINT, shutting down Bridge...
6.3.2021, 14:22:26 Initializing HAP-NodeJS v0.9.2...
6.3.2021, 14:22:27 Loaded plugin 'homebridge-platform-wemo'
6.3.2021, 14:22:27 [3/6/2021, 6:22:27 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
6.3.2021, 14:22:27 Loading 1 platforms...
6.3.2021, 14:22:27 [Wemo] Initializing BelkinWeMo platform...
6.3.2021, 14:22:27 [Wemo] [v2.14.0] initialised. Setting up device discovery.
6.3.2021, 14:22:27 [Wemo] [EG Bad] has been removed from Homebridge.
6.3.2021, 14:22:27 [Wemo] Listener server port [45565].
6.3.2021, 14:22:27 [Wemo] ✓ Setup complete. Have a feature request? Visit http://bit.ly/hb-wemo-issues to ask!
6.3.2021, 14:22:27 Preparing Advertiser for 'HOOBS CD0E' using bonjour-hap backend!
6.3.2021, 14:22:27 Starting to advertise 'HOOBS CD0E' using bonjour-hap backend!
6.3.2021, 14:22:27 Bridge is running on port 51826.
6.3.2021, 14:22:27 [Wemo] [Weihnachtsbeleuchtung] initialising with options {"disableDeviceLogging":false}.
6.3.2021, 14:22:27 [Wemo] [Weihnachtsbeleuchtung] initial subscription for service [urn:Belkin:service:basicevent:1].
6.3.2021, 14:22:27 [Wemo] [Weihnachtsbeleuchtung] initialised with s/n 221403K1101830 and mac address B4:75:0E:71:D3:A8.
6.3.2021, 14:22:27 [Wemo] [uuid:Socket-1_0-221403K1101830] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>1</BinaryState>
</e:property>
</e:propertyset>


6.3.2021, 14:22:27 [Wemo] [Weihnachtsbeleuchtung] received update [binaryState: 1].
6.3.2021, 14:22:28 [Wemo] [OG Yoga Zimmer Leselicht] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableDeviceLogging":false}.
6.3.2021, 14:22:28 [Wemo] [WeMo Link] initial subscription for service [urn:Belkin:service:bridge:1].
6.3.2021, 14:22:28 [Wemo] [OG Yoga Zimmer Leselicht] initialised with s/n 94103EF6BF427018 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:22:28 [Wemo] [Terrasse] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableDeviceLogging":false}.
6.3.2021, 14:22:28 [Wemo] [WeMo Link] subscription still pending.
6.3.2021, 14:22:28 [Wemo] [Terrasse] initialised with s/n 94103EF6BF42D754 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:22:28 [Wemo] [UG Katzentreppe] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableDeviceLogging":false}.
_**_6.3.2021, 14:22:28 [Wemo] [WeMo Link] subscription still pending._**_
6.3.2021, 14:22:28 [Wemo] [UG Katzentreppe] initialised with s/n 94103EF6BF42E807 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:22:28 [Wemo] [OG Yoga Zimmer Ambiente] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableDeviceLogging":false}.
6.3.2021, 14:22:28 [Wemo] [WeMo Link] subscription still pending.
6.3.2021, 14:22:28 [Wemo] [OG Yoga Zimmer Ambiente] initialised with s/n 94103EA2B2789161 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:22:28 [Wemo] [EG Bad] has been added to Homebridge.
6.3.2021, 14:22:28 [Wemo] [EG Bad] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableDeviceLogging":false}.
6.3.2021, 14:22:28 [Wemo] [WeMo Link] subscription still pending.
6.3.2021, 14:22:28 [Wemo] [EG Bad] initialised with s/n 94103EA2B278AE1F and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:22:28 [Wemo] [EG Bistro] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableDeviceLogging":false}.
6.3.2021, 14:22:28 [Wemo] [WeMo Link] subscription still pending.
6.3.2021, 14:22:28 [Wemo] [EG Bistro] initialised with s/n 94103EA2B278BF75 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:22:28 [Wemo] [uuid:Bridge-1_0-231448B01004D8] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<StatusChange></StatusChange>
</e:property>
<e:property>
<SubDeviceFWUpdateStatus></SubDeviceFWUpdateStatus>
</e:property>
</e:propertyset>


6.3.2021, 14:22:28 [Wemo] [uuid:Bridge-1_0-231448B01004D8] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<TimeSyncRequest>0</TimeSyncRequest>
</e:property>
</e:propertyset>


6.3.2021, 14:22:28 [Wemo] [uuid:Bridge-1_0-231448B01004D8] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<TimeZoneNotification>005</TimeZoneNotification>
</e:property>
</e:propertyset>


6.3.2021, 14:22:28 [Wemo] [Gartenlicht Garage] initialising with options {"disableDeviceLogging":false}.
6.3.2021, 14:22:28 [Wemo] [Gartenlicht Garage] initial subscription for service [urn:Belkin:service:basicevent:1].
6.3.2021, 14:22:28 [Wemo] [Gartenlicht Garage] initialised with s/n 221304K11000AD and mac address EC:1A:59:84:1E:24.
**6.3.2021, 14:22:28 [Wemo] [EG Bad] device appears to be offline.**
6.3.2021, 14:22:28 [Wemo] [uuid:Socket-1_0-221304K11000AD] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>1</BinaryState>
</e:property>
</e:propertyset>


6.3.2021, 14:22:28 [Wemo] [Gartenlicht Garage] received update [binaryState: 1].
'''

**Comment by Schattenkaiser** [comment]
additional new findings
'''
6.3.2021, 14:39:11 [Wemo] Initializing BelkinWeMo platform...
6.3.2021, 14:39:11 [Wemo] [v2.14.0] initialised. Setting up device discovery.
**6.3.2021, 14:39:12 [Wemo] [EG Bad] has been removed from Homebridge.**
6.3.2021, 14:39:12 [Wemo] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
6.3.2021, 14:39:12 Preparing Advertiser for 'HOOBS CD0E' using bonjour-hap backend!
6.3.2021, 14:39:12 Starting to advertise 'HOOBS CD0E' using bonjour-hap backend!
6.3.2021, 14:39:12 Bridge is running on port 51826.
6.3.2021, 14:39:12 [Wemo] [Weihnachtsbeleuchtung] initialised with s/n 221403K1101830 and mac address B4:75:0E:71:D3:A8.
6.3.2021, 14:39:12 [Wemo] [OG Yoga Zimmer Leselicht] initialised with s/n 94103EF6BF427018 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:39:12 [Wemo] [Terrasse] initialised with s/n 94103EF6BF42D754 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:39:12 [Wemo] [UG Katzentreppe] initialised with s/n 94103EF6BF42E807 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:39:12 [Wemo] [OG Yoga Zimmer Ambiente] initialised with s/n 94103EA2B2789161 and mac address 94:10:3E:CD:60:2C.
**6.3.2021, 14:39:12 [Wemo] [EG Bad] has been added to Homebridge.**
**6.3.2021, 14:39:12 [Wemo] [EG Bad] initialised with s/n 94103EA2B278AE1F** and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:39:12 [Wemo] [EG Bistro] initialised with s/n 94103EA2B278BF75 and mac address 94:10:3E:CD:60:2C.
6.3.2021, 14:39:12 [Wemo] [Gartenlicht Garage] initialised with s/n 221304K11000AD and mac address EC:1A:59:84:1E:24.
**6.3.2021, 14:39:12 [Wemo] [EG Bad] device appears to be offline.**
'''

**Comment by Schattenkaiser** [comment]
@bwp91 
Thanks for support - the problem seems to be fixed (for the moment)
I've set the following steps

- shutdown Raspberry Pi
- reset Wemo-Link
- reset Wemo-Bridge
- add Wemo-Bridge to HomeKit App on iPhone again
- restart Wemo-Link
- restart Raspberry Pi with Hoobs

The result is looking not that bad, even as also the EG Bad Bulb doesn't appear any longer. The only thing to solve is, that even the other bulbs are not connected so far

```
6.3.2021, 14:49:16 HOOBS listening on port 80.
6.3.2021, 14:49:17 Initializing HAP-NodeJS v0.9.2...
6.3.2021, 14:49:18 Loaded plugin 'homebridge-platform-wemo'
6.3.2021, 14:49:18 [3/6/2021, 6:49:18 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
6.3.2021, 14:49:18 Loading 1 platforms...
6.3.2021, 14:49:18 [Wemo] Initializing BelkinWeMo platform...
6.3.2021, 14:49:18 [Wemo] [v2.14.0] initialised. Setting up device discovery.
6.3.2021, 14:49:18 [Wemo] [EG Bad] has been removed from Homebridge.
6.3.2021, 14:49:18 [Wemo] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!
6.3.2021, 14:49:18 Preparing Advertiser for 'HOOBS CD0E' using bonjour-hap backend!
6.3.2021, 14:49:18 Starting to advertise 'HOOBS CD0E' using bonjour-hap backend!
6.3.2021, 14:49:18 Bridge is running on port 51826.
6.3.2021, 14:49:19 [Wemo] [Gartenlicht Garage] initialised with s/n 221304K11000AD and mac address EC:1A:59:84:1E:24.
6.3.2021, 14:49:20 [Wemo] [Weihnachtsbeleuchtung] initialised with s/n 221403K1101830 and mac address B4:75:0E:71:D3:A8.
6.3.2021, 15:25:20 [Wemo] [OG Yoga Zimmer Leselicht] awaiting (re)connection and will retry in 190s.
6.3.2021, 15:25:20 [Wemo] [Terrasse] awaiting (re)connection and will retry in 190s.
6.3.2021, 15:25:20 [Wemo] [UG Katzentreppe] awaiting (re)connection and will retry in 190s.
6.3.2021, 15:25:20 [Wemo] [OG Yoga Zimmer Ambiente] awaiting (re)connection and will retry in 190s.
6.3.2021, 15:25:20 [Wemo] [EG Bistro] awaiting (re)connection and will retry in 190s.
6.3.2021, 15:31:21 [Wemo] [Weihnachtsbeleuchtung] updating state to [on].
6.3.2021, 15:31:23 [Wemo] [Weihnachtsbeleuchtung] updating state to [off].
6.3.2021, 15:32:14 [Wemo] [Gartenlicht Garage] updating state to [on].
6.3.2021, 15:32:21 [Wemo] [Gartenlicht Garage] updating state to [off].
```

**Comment by bwp91** [comment]
Often these `awaiting connection and will retry` are fixed with time, especially if you have just reset everything.

Have they connected now?

**Comment by Schattenkaiser** [comment]
not yet, but that ain't a problem of the plugin, but a (known) issue with the wemo-link. Sometimes it's loosing connection to the home network, and it need some time to establish the connection again.

I understand that this task can be marked as resolved - thank you
