### ISSUE TITLE
Wemo V2 Dimmers

### ISSUE THREAD

**Issue by andrewk123** [bwp91/homebridge-platform-wemo#242]
It appears as if the latest versions of Wemo Devices (so far I have identified 2) have different behaviors when a subscription is created than earlier versions. The two devices I've identified so far are the Wemo WiFi Smart Plug and the Belkin Plugin Dimmer hardware version V2. Both of these have RTOS rather than OWRT in the firmwareVersion XML string.

Note: all the devices I've looked at are on the "latest" Wemo software version.

First change is that when an initial subscription is created (typically after a Homebridge reset) a push event is **not** sent with the current state to homebridge-platform-wemo.  This has the result that the switch state inside of the homebridge-platform-wemo is potentially incorrect until the device state changes (when a push event is (correctly) sent).

The above issue applies to both of the devices.  The second issue is specific to the dimmer only.  V1 of the Wemo dimmer sends out a push message when the brightness value changes and homebridge-platform-wemo correctly updates its brightness value. V2 **does not** send out a brightness push message (brightness appears to be only to be available via GetBinaryState with the result that the brightness shown in the homebridge-platform-wemo is is potentially incorrect and is only updated when the switch transitions from off to on. 

This all was tested in Homebridge 1.3.2 and homebridge-platform-wemo 2.14.0 running on a Pi 3B+ under Buster.

Looking at the dimmer connected "natively" to HomeKit the brightness value **is** updated in real time, so it appears there might be a mechanism to obtain the information (perhaps via a different subscription mechanism).

Let me know if I can assist with debugging any of this.

**Comment by bwp91** [comment]
Hi @andrewk123 

Thanks for these observations.

With regards to the "first" issue you have mentioned, could you try the latest beta of the plugin, 2.14.1-1, to see if this makes a difference? The changes I have made are that when a device is discovered and initialised into Homebridge, the plugin will make an immediate request for the current state of the device, rather than relying on a push event (which you have noted doesn't happen with the newer devices).

If this change makes a difference then I will look into the "second" issue you have mentioned with regards to the brightness.

Thanks!

**Comment by andrewk123** [comment]
Ben,

The first part seems to work OK on 1.3.3-Beta-9.  The status of a V2 dimmer is updated when the plug-in is restarted.  However, after power cycling the dimmer its state (neither .On or .Brightness) is updated.  It appears as if the subscription gets re-established but the status does not update.  

I’m also seeing a number of “UnhandledPromiseRejectionWarning” related to timeouts however they are not against the devices we are looking at.

Andrew

**Comment by bwp91** [comment]
I could do with more info about the `UnhandledPromiseRejectionWarning`s... could you get me the full log messages with regards to these?

**Comment by andrewk123** [comment]
This is what was being generated:

[3/9/2021, 1:59:06 PM] [Wemo] [Table Light] reported error and will retry connection within undefineds [ECONNABORTED: timeout of 10000ms exceeded].
(node:23344) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/adapters/http.js:280:16)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/follow-redirects/index.js:165:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/9/2021, 1:59:06 PM] [Wemo] [Rear Door] reported error and will retry connection within undefineds [ECONNABORTED: timeout of 10000ms exceeded].
(node:23344) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/adapters/http.js:280:16)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/follow-redirects/index.js:165:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:23344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)


[3/10/2021, 6:05:54 AM] [Wemo] [http://192.168.58.204:49154/setup.xml] connection error: timeout of 10000ms exceeded at createError (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/core/createError.js:16:15).
[3/10/2021, 6:06:01 AM] [Wemo] [Overhead Light] reported error and will retry connection within undefineds [ECONNABORTED: timeout of 10000ms exceeded].
(node:6980) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/axios/lib/adapters/http.js:280:16)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/follow-redirects/index.js:165:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:6980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bwp91** [comment]
Have you only encountered these messages since updating to the beta?

**Comment by bwp91** [comment]
The `UnhandledPromiseRejectionWarning`s should be fixed in the latest beta of the plugin.

So with regards to the dimmer (v2), does any 'incoming notification' appear in the logs when you turn the device on/off or change the brightness?

**Comment by andrewk123** [comment]
OK… 

Now testing on 1.3.4 Beta0

In my test setup I have a V1 dimmer and a V2 dimmer:

In both cases, starting from each dimmer in the off state off (but set to 100% brightness) I turned the dimmer on and then changed the brightness to 50% (all via the Wemo App)

V1 Dimmer (Dining Room Light):

Set dimmer on
[3/10/2021, 7:31:46 AM] [Wemo] [Dining Room Light] updating state to [on].
[3/10/2021, 7:31:46 AM] [Wemo] [Dining Room Light] updating brightness to [100%].

Change brightness to 50%
[3/10/2021, 7:31:55 AM] [Wemo] [Dining Room Light] updating brightness to [50%].


V2 Dimmer (Spare Dimmer)

Set dimmer on
[3/10/2021, 7:30:41 AM] [Wemo] [Spare Dimmer] updating state to [on].
[3/10/2021, 7:30:41 AM] [Wemo] [Spare Dimmer] updating brightness to [100%].

Change brightness to 50%
No log generated and brightness in plugin does not change.  

As far as I can see the V2 dimmers do not generate push messages on brightness change only after binary status change. 

Assuming I’m reading the XML correctly (I may not be) this appears to be by design.

V1 Dimmer
<serviceStateTable>
<stateVariable sendEvents="yes">
<name>BinaryState</name>
<dataType>string</dataType>
<defaultValue>0</defaultValue>
</stateVariable>
<stateVariable sendEvents="no">
<name>Duration</name>
<dataType>string</dataType>
<defaultValue>0</defaultValue>
</stateVariable>
<stateVariable sendEvents="no">
<name>EndAction</name>
<dataType>string</dataType>
<defaultValue>0</defaultValue>
</stateVariable>
<stateVariable sendEvents="yes">
<name>brightness</name>
<dataType>string</dataType>
<defaultValue>100</defaultValue>
</stateVariable>


V2 Dimmer
<serviceStateTable>
<stateVariable sendEvents="yes">
<name>BinaryState</name>
<dataType>string</dataType>
</stateVariable>
<stateVariable sendEvents="no">
<name>Duration</name>
<dataType>string</dataType>
</stateVariable>
<stateVariable sendEvents="no">
<name>EndAction</name>
<dataType>string</dataType>
</stateVariable>
<stateVariable sendEvents="no">
<name>brightness</name>
<dataType>string</dataType>
</stateVariable>

Having said all that brightness is updated in real time when looking at the V2 dimmer from HomeKit so the mechanism still exists somewhere…. At a guess it needs an additional subscription or an additional flag in the existing subscription.

Hope this helps.

**Comment by andrewk123** [comment]
On the V2 dimmer I get the <BinaryState>{state}</BinaryState> notification when the state changes but not the <Brightness>{brightness}</Brightness> message when the brightness changes.

I get both messages when using the V1 dimmer.

Here is the brightness notification from the V1 dimmer.  It is not generated by the V2 dimmer.

<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<Brightness>51</Brightness>
</e:property>
</e:propertyset>

**Comment by bwp91** [comment]
Okay, what I am trying to work out is whether the brightness on the v2 is contained within the BinaryState notification. On the v2, what does {state} look like in the <BinaryState>{state}</BinaryState> notification?

**Comment by andrewk123** [comment]
It is not contained inside the state notification.  The V2 state notification looks like this (identical to the V1 notification).

<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>1</BinaryState>
</e:property>
</e:propertyset>

**Comment by bwp91** [comment]
Might have to resort to my greatest hate... polling for updates 😖

I am unsure as to how the native homekit accessory is getting the info in real time. might even be that it doesn't use upnp at all.

**Comment by andrewk123** [comment]
Potentially dumb question..  does Alexa or Google Home use the same interface as we do?

**Comment by bwp91** [comment]
I’m not sure. I’d imagine somehow they use the wemo cloud data like the wemo app.

**Comment by andrewk123** [comment]
I found this… it is talking about a Wemo Emulator based on an ESP8266 talking to Alexa.

If correct it looks like the same interface we are using.  If so them maybe at some point there will be pressure on Belkin to fix the interface on their newer equipment?

https://www.instructables.com/Alexa-NodeMCU-WeMo-Emulation-Made-Simple/ <https://www.instructables.com/Alexa-NodeMCU-WeMo-Emulation-Made-Simple/>

Andrew

**Comment by bwp91** [comment]
Latest beta version of the plugin includes a configurable polling option for the these newer Dimmers that don't automatically send brightness updates to the plugin.

I don't own a dimmer at all so can't really test, could you give it a try?

Thanks

**Comment by andrewk123** [comment]
Ben,

I’m now testing with: v2.14.1-5

My plugin configuration is:

 {
            "name": "Wemo",
            "mode": "auto",
            "debug": true,
            "wemoLights": [
                {
                    "serialNumber": “XXX",
                    "pollingInterval": 15
                }
            ],
            "platform": "BelkinWeMo"
        }

XXX is the serial number of the V2 dimmer.

Unfortunately I’m not seeing any update when changing the V2 Dimmer brightness from the Wemo App,

I’m not seeing any log updates either (I’m running the plugin in debug mode).

Andrew

**Comment by bwp91** [comment]
My bad!
Please try v2.14.1-6

**Comment by andrewk123** [comment]
Yep… that works as advertised.

Nice job… though I wish there was a push based solution.  Any point in trying to beat on Belkin to fix it?

**Comment by bwp91** [comment]
Not sure. Could be due to the fact (if i’m right i’m thinking) these newer models are native homekit anyway?

My slight concern now is that newer models of their other products might not send automatically send such attributes like the brightness for the dimmer. 

Perhaps with a firmware update in due course it might change.

And i agree with the polling - i’m not a fan of it all - it doesn’t feel “Apple” 🤣

**Comment by andrewk123** [comment]
Ben,

I agree newer models are HomeKit however Homekit is not the only subscriber to this interface.  It appears that Alexa uses the same interface as we are.

I think (unless you think there is a downside to it) I will raise something with Belkin.  It won’t directly go anywhere is my guess but it might get it lodged in their system.

A

**Comment by bwp91** [comment]
> unless you think there is a downside to it

No downside at all... nothing to lose by trying... let me know (if and!) when you get a response from them :)

**Comment by bwp91** [comment]
Will close this issue for now… as the workaround is in place… but @andrewk123 if you ever do a firmware update of the dimmer so check to see if the `sendEvents` has changed to yes!
