### ISSUE TITLE
node.js update message doesn't reflect my current node.js version correctly

### ISSUE THREAD

**Issue by chaz-clark** [bwp91/homebridge-platform-wemo#243]
The plugin has an upgrade from v12.13.0. Typing node -v in my console gives v15.11.0. Following the link to git hub to update Node.js running the code "sudo hb-service update-node" returns "already-up-to-date". Is this happening to anyone else? 

The homebridge-platform-wemo plugin recommends running on Node.js v14.16.0 or later. You are currently running Node.js v14.15.4.

Are you sure you want to update homebridge-platform-wemo?

**Comment by bwp91** [comment]
Hi @chaz-clark 

Running `sudo hb-service update-node` should update your version of node to 14.16.0

So not sure how you have v15.11.0 installed - but this version is not recommended.

Try running `sudo hb-service update-node 14.16.0` in the terminal to see if this installs the correct version of node.

Then afterwards, go to Homebridge Settings -> Force Service Restart.

After doing this, you should no longer receive the node version warnings.

**Comment by chaz-clark** [comment]
Need some help. When i run that code I get the following:

(base)  ~/ sudo hb-service update-node 14.16.0
ℹ Installing Node.js v14.16.0 over v15.11.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /Users/chazclark/opt/anaconda3

However, in my Homebridge UI it shows this:
Node.js Version | v14.15.4

My system has two versions of node one from Anaconda and one from Homebridge. How do I update the one homebridge is referencing? is there a file path you have to go to first then update?
