### ISSUE TITLE
Deivces not appearing in hoobs

### ISSUE THREAD

**Issue by wtdeane** [bwp91/homebridge-platform-wemo#244]
### Details of your setup.
Hoobs

* Which version of Homebridge/HOOBS do you have?
3.3.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Hoobs Box
Node version: 14.16.0

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?

Running 2.15.2 published 3/21/2021.  The issue started after reinstalling Hoobs and all the plugins.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo Insight Smart Plug with Energy Monitoring

### Please paste any relevant logs below.

```
2021-03-29, 3:46:49 PM [Wemo] [Zojirishi] updating current consumption to [25W].
2021-03-29, 3:46:50 PM [Wemo] [uuid:Insight-1_0-231626K1200265] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<InsightParams>8|1616959732|681|0|4036|1209600|111|2855|2319167|9627036|8000</InsightParams>
</e:property>
</e:propertyset>


2021-03-29, 3:46:50 PM [Wemo] [7100DN] received update [insightParams: { state: 8, power: 2855, todayWm: 2319167, todayOnSeconds: 0 }].
2021-03-29, 3:46:51 PM [Wemo] [uuid:Insight-1_0-231626K1200ECC] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<InsightParams>1|1617047186|25|22158|449817|1209600|43|6225|19044878|211745018|8000</InsightParams>
</e:property>
</e:propertyset>




```

**Comment by bwp91** [comment]
Could you post the logs from when restarting HOOBS? When in the logs the devices show as initialied?
