### ISSUE TITLE
Something wrong with visualization via fakegato?

### ISSUE THREAD

**Issue by permaMonk** [bwp91/homebridge-platform-wemo#246]
Yesterday evening I upgrade HB v1.3.4 to npm v7.7.6.Since then (maybe a correlation?) the visualization of consumption via fakegato show a permanent consumption of 142 Wh / h although no washing process is pending.

See picture with daily view:
![IMG_7166](https://user-images.githubusercontent.com/60167885/113411963-66ec6a00-93b7-11eb-8f19-74988d4f4163.jpg)

See picture with hourly view. See also under "Verbrauch / consumption" = 0:
![IMG_7167](https://user-images.githubusercontent.com/60167885/113412049-956a4500-93b7-11eb-9ac5-49a7ced26215.jpg)

See picture of Wemo app. See also in operation under "Heute in Betrieb / today in operation" = < 1 min. And under "Jetzt ( now" = < 2 W:
![IMG_7168](https://user-images.githubusercontent.com/60167885/113412202-f3972800-93b7-11eb-8b01-612f91c82dda.jpg)

**Comment by permaMonk** [comment]
Just updated to npm v7.8.0. Keep an eye on whether that changes anything.

**Comment by bwp91** [comment]
I’ll have a further look into this later but the version of npm shouldn’t affect this.

Having said this, I believe the recommended versions of node and npm are v14.16.0 and whichever version of npm this installs if you use `hb-service`. I’ve kept my npm version still on v6

**Comment by permaMonk** [comment]
Ok. Mine Nodejs is  - btw - also 14.16.0.

**Comment by permaMonk** [comment]
It's gone. Since update npm v7.8.0 and now for 24 hours. I know it should have nothing to do with it at all, but since then everything is back as it should be. Strange.

**Comment by permaMonk** [comment]
Sadly I comes up again. No updates or changes have been made. Showing constant nearly 150 wh over almost 12 hour although there was no power consumption. Have to to disconnect and connect the Smart Plug. After that normal values ​​were displayed again.

**Comment by bwp91** [comment]
Could you install 3.0.2-beta.0 version to see if this helps?

**Comment by permaMonk** [comment]
Hi.

Yes I will. Little bit later this day.

But it will be difficult to find out if this will solve the problem. It’s a long term observation.

—

**Comment by bwp91** [comment]
> But it will be difficult to find out if this will solve the problem. It’s a long term observation.

Yes I understand this. Can keep this issue open during the meantime

**Comment by permaMonk** [comment]
Ok, made first the normal update to v3.0.1.

But:
[13/04/2021, 16:57:43] [Belkin WeMo] [v3.0.1] initialised. Setting up device discovery.
[13/04/2021, 16:57:44] [Belkin WeMo] ***** Disabling plugin [v3.0.1]. *****
[13/04/2021, 16:57:44] [Belkin WeMo] ***** Cannot read property 'updateCharacteristic' of undefined at /usr/local/lib/node_modules/homebridge-platform-wemo/lib/index.js:368:62. *****

Made the beta update  v3.0.2-beta.2, but unfortunately, there are still errors:
[13/04/2021, 17:03:21] [Belkin WeMo] [v3.0.2-beta.2] initialised. Setting up device discovery.
[13/04/2021, 17:03:21] [Belkin WeMo] ***** Disabling plugin [v3.0.2-beta.2]. *****
[13/04/2021, 17:03:21] [Belkin WeMo] ***** Cannot read property 'updateCharacteristic' of undefined at /usr/local/lib/node_modules/homebridge-platform-wemo/lib/index.js:368:62. *****

**Comment by bwp91** [comment]
And with 3.0.2-beta.3? (just published!)

**Comment by permaMonk** [comment]
Looks good. :)

[13/04/2021, 17:35:20] [Belkin WeMo] [v3.0.2-beta.3] initialised. Setting up device discovery.
[13/04/2021, 17:35:20] [Belkin WeMo] ✓ Setup complete. Thanks for using this plugin, I hope you find it helpful!

**Comment by bwp91** [comment]
Hi @permaMonk any update on this at all?

**Comment by permaMonk** [comment]
Hi there.
Sorry and ups. If there are nothing strange to report one forget to report back.
So in general it looks good over the whole time. But sometimes - really seldom - it’s seemed to have a little hiccup. Just only 2 times since the last incident. The visualization showed a constant consumption of approximately 50 watt over several days and in the 2. situation it shows 0 consumption over a longer period although the washing machine was running.
I solved this with take the Belkin switch out the socket and put it in again.
