### ISSUE TITLE
Wemo LED Brightness not working

### ISSUE THREAD

**Issue by stlouey** [bwp91/homebridge-platform-wemo#248]
### What issue do you have? Please be as thorough and explicit as possible.

Wemo LED Brightness not working. Log in homebridge shows "setting state to [on]." when i change the brightness but nothing happens. Works fine via the wemo app on iOS.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Use Homebridge + config-ui-x

* Which version of Homebridge/HOOBS do you have?

Homebridge version is v4.41.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi, Node.js version is v14.16.0 and NPM version is v6.14.11

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
v2.15.2

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

Product type=MZ100 
hardware version=v1
firmware version=83

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @stlouey 
Have the lightbulbs worked before with the brightness ie has something changed to make this stop working? 
Are there any messages in the logs when you try to change the brightness of a bulb?

**Comment by stlouey** [comment]
I am pretty sure at some point it used to work. Its not a feature i use much on my phone, more the on and off functionality. The Log in homebridge shows "setting state to [on]." multiple times when i slide/change the brightness but nothing else happens. This issue happens to all lights. Doing the same thing using the Wemo app works as intended.

**Comment by bwp91** [comment]
Could you update to the 3.0.1-beta.2 version of the plugin and let me know what it says in the logs when you try to control the brightness? just to confirm, this led bulb is connected via a wemo link?

**Comment by stlouey** [comment]
Updated to the beta version and all is working fine now. The log now shows setting brightness to [x%], instead of showing setting state to [on] when adjusting brightness. Confirming that LED are connected via Wemo link. Thanks

**Comment by bwp91** [comment]
Fab this version has now been released so hoping everything is working properly for you. I'll mark this as complete now but any further issues do let me know!
