### ISSUE TITLE
HOOBS service stops after WEMO loads

### ISSUE THREAD

**Issue by MartinKirkby** [bwp91/homebridge-platform-wemo#254]
### What issue do you have? Please be as thorough and explicit as possible.

HOOBS service is stopped after WEMO loads

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

Latest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?

Latest

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

Maker

### Please paste any relevant logs below.

```

/04/2021, 19:16:51 [Belkin WeMo] [v3.0.7] initialised. Setting up device discovery.
30/04/2021, 19:16:54 [Belkin WeMo] ✓ Setup complete. Thanks for using this plugin, I hope you find it helpful!
30/04/2021, 19:16:54 Error: bind EADDRINUSE 0.0.0.0:9761
    at dgram.js:334:20
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
30/04/2021, 19:16:55 Got SIGTERM, shutting down Bridge...

```

**Comment by mkellsy** [comment]
The `Error: bind EADDRINUSE 0.0.0.0:9761` means that port 9761 is already in use.
Edit your config and change the port to another number.
