### ISSUE TITLE
Alexa Devices gets server unresponsive 

### ISSUE THREAD

**Issue by 34Nismo** [bwp91/homebridge-platform-wemo#255]
### 1 Homebridge, and Alexa devices 

* Homebridge version 1.3.4

* Homebridge running on raspberry pie

* Wemo Ver 3.0.7

* it seems to be all the devices. they show a banner server unresponsive under the device but when selecting sometimes it responds.

![IMG_0720](https://user-images.githubusercontent.com/79167931/116798549-97aae680-aabe-11eb-85f4-35779b933e4c.jpeg)
![IMG_0721](https://user-images.githubusercontent.com/79167931/116798550-98437d00-aabe-11eb-8d0e-bfd5ccc88662.jpeg)

**Comment by bwp91** [comment]
Hi @34Nismo 

I'm struggling to understand how this issue has anything to do with the plugin since this plugin is used to expose wemo devices to homebridge/homekit, not alexa.
