### ISSUE TITLE
WEMO Maker (Garage Door) disappeared with 3.0.9

### ISSUE THREAD

**Issue by degofedal** [bwp91/homebridge-platform-wemo#256]
### What issue do you have? Please be as thorough and explicit as possible.
Updated from 3.0.8 to 3.0.9 to find that my WEMO Maker (Garage Door) disappeared from Homebridge/Apple Home app. Now i cannot get it to show up no matter what i try.

### Steps taken to resolve
- Remove "single" and "all" cached accessories in Homebridge settings 
- Change from CIAO to Bonjour HAP mDNS advertiser in Homebridge settings
- Set explicit network interface in Homebridge settings
- Enable logs in both Wemo plugin settings and Homebridge settings
- Install Wemo plugin version 3.0.7, 3.0.8 and 3.0.10-beta.0
- Enable "SSDP Explicit Socket Bind" in Wemo settings
- Completely uninstall and reinstall the Wemo plugin

### Details of your setup.
Latest Homebridge + config-ui via Docker on Synology NAS

* Which version of Homebridge/HOOBS do you have?
Homebridge 1.3.4
Node.js Version 14.16.1
Npm Version 6.14.12

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Docker on Synology NAS 

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
Issue started when upgrading to 3.0.9 (was working fine on 3.0.8).

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
WEMO Maker

### Please paste any relevant logs below.

```
[5/12/2021, 12:27:52 PM] [Wemo] Initializing BelkinWeMo platform...
[5/12/2021, 12:27:52 PM] [Wemo] [v3.0.10-beta.0] initialised. Setting up device discovery.
[5/12/2021, 12:27:52 PM] [Wemo] Listener server port [45748].
[5/12/2021, 12:27:54 PM] [Wemo] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
```

**Comment by bwp91** [comment]
Hi @degofedal 

Sounds more like a discovery issue to me since even rolling back a couple of versions hasn't helped. Has anything changed in your network setup? 

Some trivial checks

* Verify that your maker is connected to your local network
* Make sure for any reason this device isn't in your wemo config ignore list
* If the device is on a separate vlan, does Homebridge have an IP allocated on this vlan?
* Also revert your Homebridge mdns advertiser and wemo config network settings to how they were at the time it was working
* Has there been any recent firmware update to the maker?

**Comment by degofedal** [comment]
> Hi @degofedal
> 
> Sounds more like a discovery issue to me since even rolling back a couple of versions hasn't helped. Has anything changed in your network setup?
> 
> Some trivial checks
> 
> * Verify that your maker is connected to your local network
> * Make sure for any reason this device isn't in your wemo config ignore list
> * If the device is on a separate vlan, does Homebridge have an IP allocated on this vlan?
> * Also revert your Homebridge mdns advertiser and wemo config network settings to how they were at the time it was working
> * Has there been any recent firmware update to the maker?

Really strange issue, you might be right right about the discovery issue. Seems like the connection to the Home app has been severed. Unfortunately network settings haven't changed and i have no vlan's or other fancy setup. 
I can control the Maker via the native Wemo IOS app and it it shows up fine in my network controller. Also no recent firmware updates to the Maker.

Adding the Wemo as a manual device via IP in the plugin gives the below logs in Homebridge. With this config it shows up in the Homebridge plugins sections and is controllable. Not showing up in Home app 

´´´
[5/12/2021, 1:07:38 PM] [Wemo] [Garage Door] has been added to Homebridge.
[5/12/2021, 1:07:38 PM] [Wemo] [Garage Door] initialising with options {"disableDeviceLogging":false,"makerTimer":20}.
[5/12/2021, 1:07:38 PM] [Wemo] [Garage Door] initial subscription for service [urn:Belkin:service:basicevent:1].
[5/12/2021, 1:07:38 PM] [Wemo] [Garage Door] initialised with s/n 221523S00XXXXX and ip/port 192.168.0.200:49154
[5/12/2021, 1:07:38 PM] [Wemo] [uuid:Maker-1_0-221523S0001296:sensor:switch] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<ParamString>1</ParamString>
</e:property>
</e:propertyset>


[5/12/2021, 1:07:38 PM] [Wemo] [Garage Door] current state [closed] (triggered externally).
´´´

**Comment by bwp91** [comment]
If the device appears in Homebridge then it really should be appearing in the Home app. The device would have been added to the HomeKit 'default' room... have you checked there?

Also if you are running wemo in a child bridge, have you added this child bridge to homekit with the QR code?

Is the maker the only device you use with the wemo plugin? or do you have other devices that are working/not working?

**Comment by degofedal** [comment]
Hmm this is really strange. 

I rolled back to 3.0.8 and pruned the config manually to "release" the plugin from its child bridge. This did the trick - also works with 3.0.9. 

Deleted the marked lines in the attached screenshot. I can't think of anything i did to cause the issue other than clicking upgrade in Homebridge UI (but i probably did). 

![Screen Shot 2021-05-12 at 14 12 49](https://user-images.githubusercontent.com/3520690/117973101-40154200-b32c-11eb-8542-7d78be7fcef9.png)

**Comment by bwp91** [comment]
If you’re now on 3.0.9… and put the wemo plugin back into a child bridge, add the bridge to homekit, does the garage appear in home app?

**Comment by degofedal** [comment]
> If you’re now on 3.0.9… and put the wemo plugin back into a child bridge, add the bridge to homekit, does the garage appear in home app?

Sorry for taking a bit of time to get back to you. I wanted to leave it alone for a little while to check that the everything was fine.

Today I noticed that the Garage Door was unresponsive in the Home app. So I restarted homebridge. Lo and behold the Garage Door disappeared once again. I managed to get it back into Homebridge/Home app only by setting it up as at manual device. It seems that there is some intermittent problem with auto discovery with my network. Just can’t figure out what exactly.

The only IOT related setting I can think of that I have disabled is IGMP snooping, but that is not related to WiFi connectivity as far as I understand.

Really weird issue this one. I’m leaning toward a network setup issue and not a issue with the plug-in.

**Comment by bwp91** [comment]
Hey @degofedal did you manage to come to any conclusion about this? 

Does it make any difference whether you have wemo in a child bridge or not?

It’s concerning that you mentioned the accessory just “disappears” out of the home app… this should never happen… Once a device has initially been discovered it should never be removed from homebridge… even if it can’t again be discovered in the future (eg after a homebridge restart, or disconnecting the device).

The fact your device can’t be discovered automatically may well be a networking issue, but separately, i’d like to figure out the reason why the accessory is being removed from homebridge/homekit.

**Comment by degofedal** [comment]
> Hey @degofedal did you manage to come to any conclusion about this?
> 
> Does it make any difference whether you have wemo in a child bridge or not?
> 
> It’s concerning that you mentioned the accessory just “disappears” out of the home app… this should never happen… Once a device has initially been discovered it should never be removed from homebridge… even if it can’t again be discovered in the future (eg after a homebridge restart, or disconnecting the device).
> 
> The fact your device can’t be discovered automatically may well be a networking issue, but separately, i’d like to figure out the reason why the accessory is being removed from homebridge/homekit.

I just tried creating Wemo as a child bridge and added it to Homebridge. No issues whatsoever. Everything works as expected.

I'm not quite sure what exactly was the cause of the problem. However a few week ago i got an update to my Unifi Network controller and although i can't be 100% sure i believe this may have solved it. Everything has been running smoothly without issue for these last couple of weeks.

I'm sorry i can't been more specific but the issue solved it self at some point around the time i updated the Network Controller.

**Comment by bwp91** [comment]
Ah excellent. I’ll close this issue again but if you run into any problems again do let me know!

**Comment by degofedal** [comment]
> Ah excellent. I’ll close this issue again but if you run into any problems again do let me know!

I absolutely will. Also let me know if there is anything related to the WEMO Maker you need me to test out. Thanks again for your time and this fantastic plugin! Have a great weekend!
