### ISSUE TITLE
🙋🏽 Feature Request: Convert Outlet Type to Another Service Type?

### ISSUE THREAD

**Issue by vicc** [bwp91/homebridge-platform-wemo#257]
* **Please explain your feature request in a one or two sentences.**
Ability to change the service type of an `outlet` to any of the other supported types (e.g. `air purifier`?). I have a number of outlets connects to a purifier, humidifier, fan, etc. and wish they could all have different icons to better represent their tiles in the Homekit app.

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Wemo devices that this relates to?**
Wemo outlets

* **Anything else?**
I understand that some service types require many defaults that dumb devices hooked up to an outlet could never update / respond to (e.g purifier auto vs manual, purifier mode, etc), however using Apple's Homekit Accessory Simulator, it looks like it could work at least for powering on and off. 

Feel free to play around with the virtually simulated device here (From Apple's simulator app):

<img alignment="center" width="242" alt="Screen Shot 2021-05-19 at 1 16 12 AM" src="https://user-images.githubusercontent.com/1724674/118779402-d91dee80-b83f-11eb-8fdd-c627b5960baa.png">

<img alignment="center" width="400" alt="Screen Shot 2021-05-19 at 1 16 12 AM" src="https://user-images.githubusercontent.com/1724674/118779162-a2e06f00-b83f-11eb-9c60-f2d1fa005ac0.jpeg">

**Comment by bwp91** [comment]
Hi @vicc 
Please install the latest beta of the plugin and then look in the configuration ie:

<img alt="Screenshot 2021-05-19 at 12 06 41" src="https://user-images.githubusercontent.com/43026681/118803071-d2709500-b89a-11eb-9525-46c22fe4830f.png">

Make sure the 'Show As Switch' is unchecked and you should be able to set an outlet device up as an air purifier.

I can look into adding others, I just decided to start with the air purifier for now.

Let me know how you get on.

In your post you also mentioned a fan - this accessory type/icon is already available in the Home app (you can change it from a switch or outlet to a fan or light).

Next I can look into a humidifier.

I also looked into a heater, but this didn't look very good as the icon the home app uses for this accessory type is the current temperature which, obviously, is unavailable when using just an outlet device.

**Comment by bwp91** [comment]
Just as the heater/cooler accessory requires the current temperature, the humidifier/dehumidifier accessory requires the current relative humidity. So looks like the only accessory type that plays nicely is the purifier.

**Comment by bwp91** [comment]
In the latest version of the plugin there is now the option to expose a wemo outlet as an air purifier.

As I stated before, heater and de/humidifier isn’t possible as a current temperature and humidity is required.

Hope this helps.

**Comment by vicc** [comment]
Purifier worked perfectly! Wish there was a way we could read the humidity levels from another sensor and trick the system into thinking it's all one unit. For that, it might make more sense just purchasing a smart humidifier though (out of scope for this request lol). Thanks for putting in the work and giving this a try!
