### ISSUE TITLE
Change in wemo name is not reflected in Homebridge

### ISSUE THREAD

**Issue by dburr** [bwp91/homebridge-platform-wemo#258]
I recently changed the name of several of my WeMos using the WeMo app. Interestingly, the new names are correctly showing up in HomeKit, however HomeBridge still calls them by their old names (in the logs, accessories screen, etc.) Is there any way of fixing this so that the correct name is shown in Homebridge too?

**Comment by dburr** [comment]
Never mind, I ended up deleting my homebridge persistent data and restarting.

**Comment by bwp91** [comment]
Hi @dburr 

Removing the accessory cache is indeed the way i would have suggested to update the names in homebridge.

The name of any accessory is taken from the wemo device info only when it is added to homebridge. From then on there is no relationship between device names in wemo and in homebridge. So removing from the cache is the only way to update the homebridge name.

Glad you got it sorted anyway!
