### ISSUE TITLE
Wemo Maker for Garage door is backwards

### ISSUE THREAD

**Issue by MatGriffin** [bwp91/homebridge-platform-wemo#259]
### What issue do you have? Please be as thorough and explicit as possible.
I've been using a Wemo Maker for a while as a Garage door opener, for some reason its reporting in Home app reversed. So when the door is closed HK states "opening" and vice versa but in Homebridge accessories section it's correct, when the door is closed its says closing.  Note I've put "opening" and "closing"  not open or closed. In the home app it never says closed or open on the button tile just opening or closing and the motion icon is spinning in the top right of the button.

### Details of your setup.
(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?
1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Homebridge
Raspberry Pi 3
Node.js Version v14.17.1
Npm Version v6.14.13

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
 v3.1.0
 Seems to have just started not sure why though

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.
Wemo Maker

**Comment by bwp91** [comment]
Hi @MatGriffin 
Does your wemo maker have a sensor attached? Is there _any_ chance that this may have stopped working somehow and causing these problems?
