### ISSUE TITLE
v3.2.0 Cannot find module './device/switch'

### ISSUE THREAD

**Issue by DMBlakeley** [bwp91/homebridge-platform-wemo#262]
### What issue do you have? Please be as thorough and explicit as possible.
Updated to v3.2.0 through Config UI and received the following error:

`[7/7/2021, 7:34:54 AM] [Wemo] [Front Porch Lights] could not be initialised as Cannot find module './device/switch'
Require stack:
- /usr/local/lib/node_modules/homebridge-platform-wemo/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridgeRequire stack:.`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Using Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
MacOS v11.4
Node.js v14.7.3
npm v16.14.13

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?
v1.3.2, not an issue with v1.3.1

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

(3) Wemo light switches v1 

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Oops! Does beta version 3.2.1-beta.0 fix this?

**Comment by DMBlakeley** [comment]
Yes, thanks for quick response.
