### ISSUE TITLE
Config Example

### ISSUE THREAD

**Issue by vijaydembla1** [bwp91/homebridge-platform-wemo#264]
Hi,

I have several Wemo devices and they all seem to work fine. I wish to manually config one of the devices, unfortunately, I'm unable to find an example here that could help me to discover several devices, but one of them to be loaded with options that are configured manually.

I have a wemo motion sensor and I wish to change it's nomotiontimer to 10 seconds, unfortunately it goes with the default option of 60 seconds.

My config below is able to detect all devices, but unable to load Wemo sensor with it's manually configured options:

{
            "platform": "BelkinWeMo",
            "name": "WeMo",
            "expected_accessories": "20",
            "discoveryInterval": "30",
            "homekit_safe": "1",
            "serialNumber": "***",
            "label": "Wemo Sensor",
            "noMotionTimer": 10,
            "overrideLogging": "disable"
        }

The home bridge console loads the wemo sensor as below:

[7/10/2021, 2:34:45 AM] [WeMo] [WeMo Motion] initialising with options {"logging":"standard","noMotionTimer":60}.
[7/10/2021, 2:34:45 AM] [WeMo] [WeMo Motion] initialised with s/n ** and ip/port **

Any help will be greatly appreciated :-)

Thanks

**Comment by bwp91** [comment]
Hi @vijaydembla1

A config like this should get you going:

```json
{
  "platform": "BelkinWeMo",
  "name": "WeMo",
  "discoveryInterval": "30",
  "wemoMotions":  [
    {
      "serialNumber": "***",
      "label": "Wemo Sensor",
      "noMotionTimer": 10,
      "overrideLogging": "disable"
    }
  ]
}
```

I've removed the `expected_accessories` and `homekit_safe` entries since they are no longer used.

**Comment by vijaydembla1** [comment]
Brilliant!!!

Thanks a ton, it worked :-)

Thanks again..
