### ISSUE TITLE
Wemo maker sensor state is reversed in homebridge

### ISSUE THREAD

**Issue by averagejoe777** [bwp91/homebridge-platform-wemo#265]
### Details of setup.
(1) Homebridge UI-X

###version of Homebridge
1.3.4

###Platform  Homebridge is on
Raspberry Pi with node 14.17.2  and npm 6.14.13

### version of the plugin (homebridge-platform-wemo)
I'm new to the plugin but experiencing the issue on  the latest version 3.2.2. I've tried rolling it back to a previous version and have been unsuccessful. Currently verision 3.0.5 is installed and having the same issue

*Issue is with the wemo maker sensor state.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi,

Do you have the wemo makers exposed in homebridge as a garage door, or a switch + contact sensor?

**Comment by averagejoe777** [comment]
Initially it was set up to the default option when it was discovered by the auto option

I've since gone and changed it to contact and switch and the issue is present

**Comment by bwp91** [comment]
Can you use the plugin settings to turn on debug logging, then get me all the homebridge log entries that are generated from opening/closing or closing/opening the door ie a full cycle either way.

thanks

**Comment by averagejoe777** [comment]
here  are the logs when it is first enabled on plugin start up;

[21/07/2021, 11:53:01] [Wemo] [Sliding Door] current state [on].
[21/07/2021, 11:53:01] [Wemo] [Sliding Door] current contact [detected].
[21/07/2021, 11:53:01] [Wemo] [uuid:Maker-1_0-221439S0000732:sensor:switch] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<ParamString>1</ParamString>
</e:property>
</e:propertyset>


Here it is for a full cycle opening and closing. Please note that i have a reed sensor on the wemo maker for the sliding door. The door was closed to start, i then opened it, and closed it to generate the log

[21/07/2021, 11:56:05] [Wemo] [uuid:Maker-1_0-221439S0000732:sensor:switch] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<attributeList>&lt;attribute&gt;&lt;name&gt;Sensor&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;prevalue&gt;1&lt;/prevalue&gt;&lt;ts&gt;1626864963&lt;/ts&gt;&lt;/attribute&gt;</attributeList>
</e:property>
</e:propertyset>
[21/07/2021, 11:56:05] [Wemo] [Sliding Door] receiving update [Sensor: 0].
[21/07/2021, 11:56:05] [Wemo] [Sliding Door] current contact [not detected].
[21/07/2021, 11:56:18] [Wemo] [uuid:Maker-1_0-221439S0000732:sensor:switch] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<attributeList>&lt;attribute&gt;&lt;name&gt;Sensor&lt;/name&gt;&lt;value&gt;1&lt;/value&gt;&lt;prevalue&gt;0&lt;/prevalue&gt;&lt;ts&gt;1626864976&lt;/ts&gt;&lt;/attribute&gt;</attributeList>
</e:property>
</e:propertyset>
[21/07/2021, 11:56:18] [Wemo] [Sliding Door] receiving update [Sensor: 1].
[21/07/2021, 11:56:18] [Wemo] [Sliding Door] current contact [detected].

**Comment by bwp91** [comment]
I've noticed an issue with the logging, that the `current contact [detected]` and `current contact [not detected]` are incorrectly switched when the plugin receives an update from the wemo maker sensor. I will fix this in a new version shortly. But this is the only issue?

The sensor reports to the plugin a value of `0` when contact is detected - ie a garage door is closed, and reports a value of `1` when contact is not detected - ie a garage door is open.

Regardless of the logging, the state of the sensor in homebridge/homekit should appear, and be updated correctly when it receives a `0` or `1` value from the device.

**Comment by averagejoe777** [comment]
I think it might be affecting more then just the logging (and I apologize if you already explained that in the last paragraph)

The issue does extend into homebridge. I noticed it the config-ui-x screen under accessories

It also reports as open in HomeKit  despite it actually being closed![image](https://user-images.githubusercontent.com/87743489/126498394-a724414e-0aa7-4de4-8996-78fd08176b23.jpeg)

**Comment by bwp91** [comment]
What the issue seems to be here, is your wemo maker reporting a 'reversed' state to the plugin when your door opens and closes. As I mentioned before, normally the sensor reports `0` for closed and `1` for open. However your device is reporting `0` for open and `1` for closed, as from your logs earlier when you did an open/close cycle, the device reported to the plugin:

```
[21/07/2021, 11:56:05] [Wemo] [Sliding Door] receiving update [Sensor: 0]. (open)
[21/07/2021, 11:56:18] [Wemo] [Sliding Door] receiving update [Sensor: 1]. (closed)
```

So whilst the plugin is in fact behaving correctly, the reverse reporting of your sensor is leading to the reversed states in homebridge/homekit.

Can you update to the beta version of the plugin I have just pushed, v3.2.3-beta.1, and then use the plugin settings to tick the new option 'Reverse Polarity':

<img width="400" alt="Screenshot 2021-07-21 at 17 07 30" src="https://user-images.githubusercontent.com/43026681/126522269-ac799e50-50d0-4b39-9ad8-72c499af2fbb.png">

Restart the plugin, and the states should show correctly.

Let me know!

**Comment by averagejoe777** [comment]
It's fixed and working great! Thank you so much for adding the option to reverse the polarity!
